import { maxBitsForList, takeNBitsBestItemsOf } from "./utils";
import { IWordbank } from "../IWordbank";

const ADJECTIVES_ALL = [
  "able", // VoA
  "adult", // VoA
  "afraid", // VoA
  "alive", // VoA
  "alone", // VoA
  "ancient", // VoA
  "awake", // VoA
  "baby", // VoA
  "back", // VoA
  "bad", // VoA
  "best", // VoA
  "better", // VoA
  "big", // VoA
  "black", // VoA
  "blue", // VoA
  "born", // VoA
  "bottom", // VoA
  "brave", // VoA
  "brief", // VoA
  "bright", // VoA
  "brown", // VoA
  "busy", // VoA
  "calm", // VoA
  "careful", // VoA
  "center", // VoA
  "chemical", // VoA
  "chief", // VoA
  "clean", // VoA
  "clear", // VoA
  "close", // VoA
  "cold", // VoA
  "common", // VoA
  "complete", // VoA
  "complex", // VoA
  "conservative", // VoA
  "cool", // VoA
  "correct", // VoA
  "cotton", // VoA
  "country", // VoA
  "current", // VoA
  "custom", // VoA
  "cut", // VoA
  "dark", // VoA
  "dead", // VoA
  "deaf", // VoA
  "deep", // VoA
  "different", // VoA
  "difficult", // VoA
  "direct", // VoA
  "dirty", // VoA
  "down", // VoA
  "dry", // VoA
  "early", // VoA
  "east", // VoA
  "easy", // VoA
  "empty", // VoA
  "equal", // VoA
  "ethnic", // VoA
  "even", // VoA
  "evil", // VoA
  "exact", // VoA
  "excellent", // VoA
  "expert", // VoA
  "express", // VoA
  "extra", // VoA
  "extreme", // VoA
  "fair", // VoA
  "false", // VoA
  "family", // VoA
  "famous", // VoA
  "far", // VoA
  "fast", // VoA
  "fat", // VoA
  "federal", // VoA
  "female", // VoA
  "fertile", // VoA
  "fierce", // VoA
  "final", // VoA
  "financial", // VoA
  "fine", // VoA
  "firm", // VoA
  "first", // VoA
  "fit", // VoA
  "flat", // VoA
  "fluid", // VoA
  "foreign", // VoA
  "former", // VoA
  "forward", // VoA
  "free", // VoA
  "fresh", // VoA
  "front", // VoA
  "full", // VoA
  "fun", // VoA
  "future", // VoA
  "general", // VoA
  "gentle", // VoA
  "glass", // VoA
  "gold", // VoA
  "good", // VoA
  "gray", // VoA
  "great", // VoA
  "green", // VoA
  "ground", // VoA
  "group", // VoA
  "guerrilla", // VoA
  "guilty", // VoA
  "half", // VoA
  "happy", // VoA
  "hard", // VoA
  "head", // VoA
  "heavy", // VoA
  "high", // VoA
  "hit", // VoA
  "holy", // VoA
  "home", // VoA
  "honest", // VoA
  "horrible", // VoA
  "hostile", // VoA
  "hot", // VoA
  "house", // VoA
  "huge", // VoA
  "human", // VoA
  "illegal", // VoA
  "immediate", // VoA
  "immigrant", // VoA
  "important", // VoA
  "independent", // VoA
  "individual", // VoA
  "innocent", // VoA
  "insane", // VoA
  "intelligent", // VoA
  "intense", // VoA
  "international", // VoA
  "iron", // VoA
  "joint", // VoA
  "just", // VoA
  "kind", // VoA
  "large", // VoA
  "last", // VoA
  "late", // VoA
  "lead", // VoA
  "left", // VoA
  "legal", // VoA
  "level", // VoA
  "liberal", // VoA
  "light", // VoA
  "liquid", // VoA
  "little", // VoA
  "live", // VoA
  "local", // VoA
  "lonely", // VoA
  "long", // VoA
  "loud", // VoA
  "low", // VoA
  "loyal", // VoA
  "main", // VoA
  "major", // VoA
  "male", // VoA
  "material", // VoA
  "mean", // VoA
  "mental", // VoA
  "metal", // VoA
  "middle", // VoA
  "militant", // VoA
  "military", // VoA
  "mineral", // VoA
  "minor", // VoA
  "minority", // VoA
  "minute", // VoA
  "missing", // VoA
  "model", // VoA
  "moderate", // VoA
  "modern", // VoA
  "narrow", // VoA
  "native", // VoA
  "natural", // VoA
  "navy", // VoA
  "near", // VoA
  "necessary", // VoA
  "neutral", // VoA
  "new", // VoA
  "next", // VoA
  "nice", // VoA
  "normal", // VoA
  "north", // VoA
  "now", // VoA
  "nuclear", // VoA
  "offensive", // VoA
  "official", // VoA
  "old", // VoA
  "only", // VoA
  "open", // VoA
  "opposite", // VoA
  "other", // VoA
  "own", // VoA
  "paper", // VoA
  "part", // VoA
  "past", // VoA
  "patient", // VoA
  "pay", // VoA
  "perfect", // VoA
  "period", // VoA
  "permanent", // VoA
  "physical", // VoA
  "pilot", // VoA
  "plastic", // VoA
  "poor", // VoA
  "popular", // VoA
  "possible", // VoA
  "power", // VoA
  "pregnant", // VoA
  "present", // VoA
  "private", // VoA
  "problem", // VoA
  "public", // VoA
  "pure", // VoA
  "quality", // VoA
  "quick", // VoA
  "quiet", // VoA
  "rare", // VoA
  "ready", // VoA
  "real", // VoA
  "realistic", // VoA
  "reasonable", // VoA
  "recent", // VoA
  "red", // VoA
  "responsible", // VoA
  "rich", // VoA
  "right", // VoA
  "rough", // VoA
  "round", // VoA
  "rubber", // VoA
  "sad", // VoA
  "safe", // VoA
  "salt", // VoA
  "same", // VoA
  "sand", // VoA
  "second", // VoA
  "secret", // VoA
  "self", // VoA
  "separate", // VoA
  "serious", // VoA
  "set", // VoA
  "several", // VoA
  "severe", // VoA
  "sharp", // VoA
  "short", // VoA
  "sick", // VoA
  "side", // VoA
  "silver", // VoA
  "similar", // VoA
  "simple", // VoA
  "single", // VoA
  "slow", // VoA
  "small", // VoA
  "smooth", // VoA
  "social", // VoA
  "soft", // VoA
  "solid", // VoA
  "south", // VoA
  "special", // VoA
  "square", // VoA
  "steel", // VoA
  "still", // VoA
  "stone", // VoA
  "straight", // VoA
  "strange", // VoA
  "strong", // VoA
  "stupid", // VoA
  "submarine", // VoA
  "sudden", // VoA
  "sure", // VoA
  "surplus", // VoA
  "sweet", // VoA
  "tall", // VoA
  "technical", // VoA
  "temporary", // VoA
  "tense", // VoA
  "terrible", // VoA
  "thick", // VoA
  "thin", // VoA
  "third", // VoA
  "through", // VoA
  "tired", // VoA
  "top", // VoA
  "total", // VoA
  "toward", // VoA
  "tragic", // VoA
  "trial", // VoA
  "true", // VoA
  "under", // VoA
  "urgent", // VoA
  "usual", // VoA
  "vicious", // VoA
  "warm", // VoA
  "weak", // VoA
  "welcome", // VoA
  "well", // VoA
  "west", // VoA
  "wet", // VoA
  "white", // VoA
  "whole", // VoA
  "wide", // VoA
  "wild", // VoA
  "willing", // VoA
  "wise", // VoA
  "wonderful", // VoA
  "worse", // VoA
  "wrong", // VoA
  "yellow", // VoA
  "young", // VoA
  "compound", // VoA
  "dense", // VoA
];

const BITS = maxBitsForList(ADJECTIVES_ALL);
const ADJECTIVES = takeNBitsBestItemsOf(ADJECTIVES_ALL, BITS, (w) => w.length);

export class AdjectiveBank implements IWordbank {
  bits() {
    return BITS;
  }

  getEntry(i: number) {
    return ADJECTIVES[i];
  }
}