import { maxBitsForList, takeNBitsBestItemsOf } from "./utils";
import { IWordbank } from "../IWordbank";

interface CountNoun {
  singular: string;
  plural: string;
}

const COUNT_NOUNS_ALL: CountNoun[] = [
  {singular: "accident", plural: "accidents"}, // VoA
  {singular: "act", plural: "acts"}, // VoA, Fry
  {singular: "action", plural: "actions"}, // Fry
  {singular: "activist", plural: "activists"}, // VoA
  {singular: "actor", plural: "actors"}, // VoA
  {singular: "adjective", plural: "adjectives"}, // Fry
  {singular: "administration", plural: "administrations"}, // VoA
  {singular: "admit", plural: "admits"}, // VoA
  {singular: "adult", plural: "adults"}, // VoA
  {singular: "age", plural: "ages"}, // VoA, Fry
  {singular: "agency", plural: "agencies"}, // VoA
  {singular: "aim", plural: "aims"}, // VoA
  {singular: "airplane", plural: "airplanes"}, // VoA
  {singular: "airport", plural: "airports"}, // VoA
  {singular: "album", plural: "albums"}, // VoA
  {singular: "ally", plural: "allies"}, // VoA
  {singular: "ambassador", plural: "ambassadors"}, // VoA
  {singular: "amount", plural: "amounts"}, // VoA, Fry
  {singular: "angle", plural: "angles"}, // Fry
  {singular: "ancestor", plural: "ancestors"}, // VoA
  {singular: "animal", plural: "animals"}, // VoA, Fry
  {singular: "anniversary", plural: "anniversaries"}, // VoA
  {singular: "answer", plural: "answers"}, // VoA, Fry
  {singular: "appeal", plural: "appeals"}, // VoA
  {singular: "apple", plural: "apples"}, // Fry
  {singular: "area", plural: "areas"}, // VoA, Fry
  {singular: "arm", plural: "arms"}, // Fry
  {singular: "army", plural: "armies"}, // VoA, Fry
  {singular: "arrest", plural: "arrests"}, // VoA
  {singular: "art", plural: "arts"}, // VoA
  {singular: "artillery", plural: "artilleries"}, // VoA
  {singular: "astronaut", plural: "astronauts"}, // VoA
  {singular: "asylum", plural: "asylums"}, // VoA
  {singular: "attack", plural: "attacks"}, // VoA
  {singular: "attempt", plural: "attempts"}, // VoA
  {singular: "automobile", plural: "automobiles"}, // VoA
  {singular: "average", plural: "averages"}, // VoA
  {singular: "award", plural: "awards"}, // VoA
  {singular: "baby", plural: "babies"}, // VoA, Fry
  {singular: "back", plural: "backs"}, // Fry
  {singular: "balance", plural: "balances"}, // VoA
  {singular: "ball", plural: "balls"}, // VoA, Fry
  {singular: "balloon", plural: "balloons"}, // VoA
  {singular: "ballot", plural: "ballots"}, // VoA
  {singular: "ban", plural: "bans"}, // VoA
  {singular: "bank", plural: "banks"}, // VoA, Fry
  {singular: "bar", plural: "bars"}, // VoA
  {singular: "barrier", plural: "barriers"}, // VoA
  {singular: "base", plural: "bases"}, // VoA, Fry
  {singular: "battle", plural: "battles"}, // VoA
  {singular: "bear", plural: "bears"}, // Fry
  {singular: "beat", plural: "beats"}, // VoA, Fry
  {singular: "beauty", plural: "beauties"}, // VoA
  {singular: "bed", plural: "beds"}, // VoA, Fry
  {singular: "being", plural: "beings"}, // Fry
  {singular: "bell", plural: "bells"}, // VoA, Fry
  {singular: "bill", plural: "bills"}, // VoA, Fry
  {singular: "bird", plural: "birds"}, // VoA, Fry
  {singular: "bit", plural: "bits"}, // Fry
  {singular: "bite", plural: "bites"}, // VoA, Fry
  {singular: "blanket", plural: "blankets"}, // VoA
  {singular: "block", plural: "blocks"}, // VoA, Fry
  {singular: "blow", plural: "blows"}, // VoA, Fry
  {singular: "board", plural: "boards"}, // Fry
  {singular: "boat", plural: "boats"}, // VoA, Fry
  {singular: "body", plural: "bodies"}, // VoA, Fry
  {singular: "boil", plural: "boils"}, // VoA
  {singular: "bomb", plural: "bombs"}, // VoA
  {singular: "bone", plural: "bones"}, // VoA, Fry
  {singular: "book", plural: "books"}, // VoA, Fry
  {singular: "border", plural: "borders"}, // VoA
  {singular: "bottle", plural: "bottles"}, // VoA
  {singular: "bottom", plural: "bottoms"}, // VoA
  {singular: "box", plural: "boxes"}, // VoA, Fry
  {singular: "boy", plural: "boys"}, // VoA, Fry
  {singular: "boycott", plural: "boycotts"}, // VoA
  {singular: "brain", plural: "brains"}, // VoA
  {singular: "branch", plural: "branches"}, // Fry
  {singular: "break", plural: "breaks"}, // VoA, Fry
  {singular: "bridge", plural: "bridges"}, // VoA
  {singular: "brief", plural: "briefs"}, // VoA
  {singular: "broadcast", plural: "broadcasts"}, // VoA
  {singular: "brother", plural: "brothers"}, // VoA, Fry
  {singular: "budget", plural: "budgets"}, // VoA
  {singular: "build", plural: "builds"}, // VoA
  {singular: "building", plural: "buildings"}, // VoA, Fry
  {singular: "bullet", plural: "bullets"}, // VoA
  {singular: "burn", plural: "burns"}, // VoA
  {singular: "burst", plural: "bursts"}, // VoA
  {singular: "bus", plural: "buses"}, // VoA
  {singular: "business", plural: "businesses"}, // VoA, Fry
  {singular: "cabinet", plural: "cabinets"}, // VoA
  {singular: "call", plural: "calls"}, // VoA
  {singular: "camera", plural: "cameras"}, // VoA
  {singular: "camp", plural: "camps"}, // VoA
  {singular: "campaign", plural: "campaigns"}, // VoA
  {singular: "can", plural: "cans"}, // VoA
  {singular: "cancer", plural: "cancers"}, // VoA
  {singular: "candidate", plural: "candidates"}, // VoA
  {singular: "capital", plural: "capitals"}, // VoA
  {singular: "capture", plural: "captures"}, // VoA
  {singular: "car", plural: "cars"}, // VoA
  {singular: "case", plural: "cases"}, // VoA
  {singular: "cat", plural: "cats"}, // VoA
  {singular: "catch", plural: "catches"}, // VoA
  {singular: "cause", plural: "causes"}, // VoA
  {singular: "ceasefire", plural: "ceasefires"}, // VoA
  {singular: "center", plural: "centers"}, // VoA
  {singular: "century", plural: "centuries"}, // VoA
  {singular: "ceremony", plural: "ceremonies"}, // VoA
  {singular: "chairman", plural: "chairmen"}, // VoA
  {singular: "champion", plural: "champions"}, // VoA
  {singular: "chance", plural: "chances"}, // VoA
  {singular: "change", plural: "changes"}, // VoA
  {singular: "charge", plural: "charges"}, // VoA
  {singular: "chase", plural: "chases"}, // VoA
  {singular: "cheat", plural: "cheats"}, // VoA
  {singular: "cheer", plural: "cheers"}, // VoA
  {singular: "chemical", plural: "chemicals"}, // VoA
  {singular: "chemistry", plural: "chemistries"}, // VoA
  {singular: "chief", plural: "chiefs"}, // VoA
  {singular: "child", plural: "children"}, // VoA
  {singular: "circle", plural: "circles"}, // VoA
  {singular: "citizen", plural: "citizens"}, // VoA
  {singular: "city", plural: "cities"}, // VoA
  {singular: "civilian", plural: "civilians"}, // VoA
  {singular: "claim", plural: "claims"}, // VoA
  {singular: "clash", plural: "clashes"}, // VoA
  {singular: "clergy", plural: "clergies"}, // VoA
  {singular: "climate", plural: "climates"}, // VoA
  {singular: "climb", plural: "climbs"}, // VoA
  {singular: "clock", plural: "clocks"}, // VoA
  {singular: "cloth", plural: "clothes"}, // VoA
  {singular: "cloud", plural: "clouds"}, // VoA
  {singular: "coal", plural: "coals"}, // VoA
  {singular: "coalition", plural: "coalitions"}, // VoA
  {singular: "coast", plural: "coasts"}, // VoA
  {singular: "coffee", plural: "coffees"}, // VoA
  {singular: "college", plural: "colleges"}, // VoA
  {singular: "colony", plural: "colonies"}, // VoA
  {singular: "color", plural: "colors"}, // VoA
  {singular: "command", plural: "commands"}, // VoA
  {singular: "comment", plural: "comments"}, // VoA
  {singular: "committee", plural: "committees"}, // VoA
  {singular: "community", plural: "communities"}, // VoA
  {singular: "company", plural: "companies"}, // VoA
  {singular: "complex", plural: "complexes"}, // VoA
  {singular: "compromise", plural: "compromises"}, // VoA
  {singular: "computer", plural: "computers"}, // VoA
  {singular: "concern", plural: "concerns"}, // VoA
  {singular: "condition", plural: "conditions"}, // VoA
  {singular: "conference", plural: "conferences"}, // VoA
  {singular: "conflict", plural: "conflicts"}, // VoA
  {singular: "conservative", plural: "conservatives"}, // VoA
  {singular: "constitution", plural: "constitutions"}, // VoA
  {singular: "container", plural: "containers"}, // VoA
  {singular: "continent", plural: "continents"}, // VoA
  {singular: "control", plural: "controls"}, // VoA
  {singular: "convention", plural: "conventions"}, // VoA
  {singular: "cook", plural: "cooks"}, // VoA
  {singular: "copy", plural: "copies"}, // VoA
  {singular: "cost", plural: "costs"}, // VoA
  {singular: "cotton", plural: "cottons"}, // VoA
  {singular: "count", plural: "counts"}, // VoA
  {singular: "country", plural: "countries"}, // VoA
  {singular: "court", plural: "courts"}, // VoA
  {singular: "cover", plural: "covers"}, // VoA
  {singular: "cow", plural: "cows"}, // VoA
  {singular: "crash", plural: "crashes"}, // VoA
  {singular: "creature", plural: "creatures"}, // VoA
  {singular: "credit", plural: "credits"}, // VoA
  {singular: "crew", plural: "crews"}, // VoA
  {singular: "crime", plural: "crimes"}, // VoA
  {singular: "criminal", plural: "criminals"}, // VoA
  {singular: "crisis", plural: "crises"}, // VoA
  {singular: "crop", plural: "crops"}, // VoA
  {singular: "cross", plural: "crosses"}, // VoA
  {singular: "crowd", plural: "crowds"}, // VoA
  {singular: "crush", plural: "crushes"}, // VoA
  {singular: "cry", plural: "cries"}, // VoA
  {singular: "culture", plural: "cultures"}, // VoA
  {singular: "cure", plural: "cures"}, // VoA
  {singular: "curfew", plural: "curfews"}, // VoA
  {singular: "current", plural: "currents"}, // VoA
  {singular: "custom", plural: "customs"}, // VoA
  {singular: "cut", plural: "cuts"}, // VoA
  {singular: "dam", plural: "dams"}, // VoA
  {singular: "damage", plural: "damages"}, // VoA
  {singular: "dance", plural: "dances"}, // VoA
  {singular: "danger", plural: "dangers"}, // VoA
  {singular: "date", plural: "dates"}, // VoA
  {singular: "daughter", plural: "daughters"}, // VoA
  {singular: "day", plural: "days"}, // VoA
  {singular: "deal", plural: "deals"}, // VoA
  {singular: "debate", plural: "debates"}, // VoA
  {singular: "debt", plural: "debts"}, // VoA
  {singular: "defeat", plural: "defeats"}, // VoA
  {singular: "deficit", plural: "deficits"}, // VoA
  {singular: "degree", plural: "degrees"}, // VoA
  {singular: "delay", plural: "delays"}, // VoA
  {singular: "demand", plural: "demands"}, // VoA
  {singular: "democracy", plural: "democracies"}, // VoA
  {singular: "desert", plural: "deserts"}, // VoA
  {singular: "design", plural: "designs"}, // VoA
  {singular: "desire", plural: "desires"}, // VoA
  {singular: "detail", plural: "details"}, // VoA
  {singular: "device", plural: "devices"}, // VoA
  {singular: "dictator", plural: "dictators"}, // VoA
  {singular: "die", plural: "dice"}, // VoA
  {singular: "diet", plural: "diets"}, // VoA
  {singular: "dig", plural: "digs"}, // VoA
  {singular: "dinner", plural: "dinners"}, // VoA
  {singular: "diplomat", plural: "diplomats"}, // VoA
  {singular: "direction", plural: "directions"}, // VoA
  {singular: "disease", plural: "diseases"}, // VoA
  {singular: "dispute", plural: "disputes"}, // VoA
  {singular: "dissident", plural: "dissidents"}, // VoA
  {singular: "distance", plural: "distances"}, // VoA
  {singular: "divide", plural: "divides"}, // VoA
  {singular: "doctor", plural: "doctors"}, // VoA
  {singular: "document", plural: "documents"}, // VoA
  {singular: "dog", plural: "dogs"}, // VoA
  {singular: "dollar", plural: "dollars"}, // VoA
  {singular: "door", plural: "doors"}, // VoA
  {singular: "dream", plural: "dreams"}, // VoA
  {singular: "drink", plural: "drinks"}, // VoA
  {singular: "drive", plural: "drives"}, // VoA
  {singular: "drug", plural: "drugs"}, // VoA
  {singular: "duty", plural: "duties"}, // VoA
  {singular: "earthquake", plural: "earthquakes"}, // VoA
  {singular: "economy", plural: "economies"}, // VoA
  {singular: "edge", plural: "edges"}, // VoA
  {singular: "effect", plural: "effects"}, // VoA
  {singular: "effort", plural: "efforts"}, // VoA
  {singular: "egg", plural: "eggs"}, // VoA
  {singular: "embassy", plural: "embassies"}, // VoA
  {singular: "emergency", plural: "emergencies"}, // VoA
  {singular: "emotion", plural: "emotions"}, // VoA
  {singular: "end", plural: "ends"}, // VoA
  {singular: "enemy", plural: "enemies"}, // VoA
  {singular: "engine", plural: "engines"}, // VoA
  {singular: "engineer", plural: "engineers"}, // VoA
  {singular: "environment", plural: "environments"}, // VoA
  {singular: "escape", plural: "escapes"}, // VoA
  {singular: "estimate", plural: "estimates"}, // VoA
  {singular: "event", plural: "events"}, // VoA
  {singular: "evil", plural: "evils"}, // VoA
  {singular: "example", plural: "examples"}, // VoA
  {singular: "exchange", plural: "exchanges"}, // VoA
  {singular: "excuse", plural: "excuses"}, // VoA
  {singular: "exercise", plural: "exercises"}, // VoA
  {singular: "experience", plural: "experiences"}, // VoA
  {singular: "experiment", plural: "experiments"}, // VoA
  {singular: "expert", plural: "experts"}, // VoA
  {singular: "export", plural: "exports"}, // VoA
  {singular: "extra", plural: "extras"}, // VoA
  {singular: "extreme", plural: "extremes"}, // VoA
  {singular: "extremist", plural: "extremists"}, // VoA
  {singular: "face", plural: "faces"}, // VoA
  {singular: "fact", plural: "facts"}, // VoA
  {singular: "factory", plural: "factories"}, // VoA
  {singular: "fair", plural: "fairs"}, // VoA
  {singular: "fall", plural: "falls"}, // VoA
  {singular: "family", plural: "families"}, // VoA
  {singular: "farm", plural: "farms"}, // VoA
  {singular: "fat", plural: "fats"}, // VoA
  {singular: "father", plural: "fathers"}, // VoA
  {singular: "fear", plural: "fears"}, // VoA
  {singular: "female", plural: "females"}, // VoA
  {singular: "fence", plural: "fences"}, // VoA
  {singular: "field", plural: "fields"}, // VoA
  {singular: "fight", plural: "fights"}, // VoA
  {singular: "film", plural: "films"}, // VoA
  {singular: "final", plural: "finals"}, // VoA
  {singular: "find", plural: "finds"}, // VoA
  {singular: "fine", plural: "fines"}, // VoA
  {singular: "finish", plural: "finishes"}, // VoA
  {singular: "fire", plural: "fires"}, // VoA
  {singular: "firework", plural: "fireworks"}, // VoA
  {singular: "firm", plural: "firms"}, // VoA
  {singular: "first", plural: "firsts"}, // VoA
  {singular: "fish", plural: "fishes"}, // VoA
  {singular: "fix", plural: "fixes"}, // VoA
  {singular: "flag", plural: "flags"}, // VoA
  {singular: "flat", plural: "flats"}, // VoA
  {singular: "float", plural: "floats"}, // VoA
  {singular: "flood", plural: "floods"}, // VoA
  {singular: "floor", plural: "floors"}, // VoA
  {singular: "flow", plural: "flows"}, // VoA
  {singular: "flower", plural: "flowers"}, // VoA
  {singular: "fluid", plural: "fluids"}, // VoA
  {singular: "fly", plural: "flies"}, // VoA
  {singular: "food", plural: "foods"}, // VoA
  {singular: "fool", plural: "fools"}, // VoA
  {singular: "foot", plural: "feet"}, // VoA
  {singular: "force", plural: "forces"}, // VoA
  {singular: "forest", plural: "forests"}, // VoA
  {singular: "form", plural: "forms"}, // VoA
  {singular: "freedom", plural: "freedoms"}, // VoA
  {singular: "friend", plural: "friends"}, // VoA
  {singular: "front", plural: "fronts"}, // VoA
  {singular: "fruit", plural: "fruits"}, // VoA
  {singular: "fuel", plural: "fuels"}, // VoA
  {singular: "funeral", plural: "funerals"}, // VoA
  {singular: "gain", plural: "gains"}, // VoA
  {singular: "game", plural: "games"}, // VoA
  {singular: "gas", plural: "gases"}, // VoA
  {singular: "general", plural: "generals"}, // VoA
  {singular: "gift", plural: "gifts"}, // VoA
  {singular: "girl", plural: "girls"}, // VoA
  {singular: "glass", plural: "glasses"}, // VoA
  {singular: "goal", plural: "goals"}, // VoA
  {singular: "god", plural: "gods"}, // VoA
  {singular: "good", plural: "goods"}, // VoA
  {singular: "government", plural: "governments"}, // VoA
  {singular: "grain", plural: "grains"}, // VoA
  {singular: "granddaughter", plural: "granddaughters"}, // VoA
  {singular: "grandfather", plural: "grandfathers"}, // VoA
  {singular: "grandmother", plural: "grandmothers"}, // VoA
  {singular: "grandson", plural: "grandsons"}, // VoA
  {singular: "gray", plural: "grays"}, // VoA
  {singular: "great", plural: "greats"}, // VoA
  {singular: "green", plural: "greens"}, // VoA
  {singular: "grind", plural: "grinds"}, // VoA
  {singular: "ground", plural: "grounds"}, // VoA
  {singular: "group", plural: "groups"}, // VoA
  {singular: "guarantee", plural: "guarantees"}, // VoA
  {singular: "guard", plural: "guards"}, // VoA
  {singular: "guerrilla", plural: "guerrillas"}, // VoA
  {singular: "guide", plural: "guides"}, // VoA
  {singular: "gun", plural: "guns"}, // VoA
  {singular: "hair", plural: "hairs"}, // VoA
  {singular: "half", plural: "halves"}, // VoA
  {singular: "harm", plural: "harms"}, // VoA
  {singular: "harvest", plural: "harvests"}, // VoA
  {singular: "hat", plural: "hats"}, // VoA
  {singular: "head", plural: "heads"}, // VoA
  {singular: "helicopter", plural: "helicopters"}, // VoA
  {singular: "hero", plural: "heroes"}, // VoA
  {singular: "hide", plural: "hides"}, // VoA
  {singular: "high", plural: "highs"}, // VoA
  {singular: "hill", plural: "hills"}, // VoA
  {singular: "history", plural: "histories"}, // VoA
  {singular: "hit", plural: "hits"}, // VoA
  {singular: "hold", plural: "holds"}, // VoA
  {singular: "hole", plural: "holes"}, // VoA
  {singular: "holiday", plural: "holidays"}, // VoA
  {singular: "home", plural: "homes"}, // VoA
  {singular: "honor", plural: "honors"}, // VoA
  {singular: "hope", plural: "hopes"}, // VoA
  {singular: "horse", plural: "horses"}, // VoA
  {singular: "hospital", plural: "hospitals"}, // VoA
  {singular: "hostage", plural: "hostages"}, // VoA
  {singular: "hotel", plural: "hotels"}, // VoA
  {singular: "hour", plural: "hours"}, // VoA
  {singular: "house", plural: "houses"}, // VoA
  {singular: "human", plural: "humans"}, // VoA
  {singular: "humor", plural: "humors"}, // VoA
  {singular: "hunt", plural: "hunts"}, // VoA
  {singular: "hurt", plural: "hurts"}, // VoA
  {singular: "husband", plural: "husbands"}, // VoA
  {singular: "idea", plural: "ideas"}, // VoA
  {singular: "immigrant", plural: "immigrants"}, // VoA
  {singular: "import", plural: "imports"}, // VoA
  {singular: "in", plural: "ins"}, // VoA
  {singular: "incident", plural: "incidents"}, // VoA
  {singular: "increase", plural: "increases"}, // VoA
  {singular: "individual", plural: "individuals"}, // VoA
  {singular: "industry", plural: "industries"}, // VoA
  {singular: "influence", plural: "influences"}, // VoA
  {singular: "insect", plural: "insects"}, // VoA
  {singular: "instrument", plural: "instruments"}, // VoA
  {singular: "insult", plural: "insults"}, // VoA
  {singular: "interest", plural: "interests"}, // VoA
  {singular: "iron", plural: "irons"}, // VoA
  {singular: "island", plural: "islands"}, // VoA
  {singular: "issue", plural: "issues"}, // VoA
  {singular: "jail", plural: "jails"}, // VoA
  {singular: "jewel", plural: "jewels"}, // VoA
  {singular: "job", plural: "jobs"}, // VoA
  {singular: "joint", plural: "joints"}, // VoA
  {singular: "joke", plural: "jokes"}, // VoA
  {singular: "judge", plural: "judges"}, // VoA
  {singular: "jump", plural: "jumps"}, // VoA
  {singular: "jury", plural: "juries"}, // VoA
  {singular: "kick", plural: "kicks"}, // VoA
  {singular: "kill", plural: "kills"}, // VoA
  {singular: "kind", plural: "kinds"}, // VoA
  {singular: "kiss", plural: "kisses"}, // VoA
  {singular: "knife", plural: "knives"}, // VoA
  {singular: "laboratory", plural: "laboratories"}, // VoA
  {singular: "lake", plural: "lakes"}, // VoA
  {singular: "land", plural: "lands"}, // VoA
  {singular: "language", plural: "languages"}, // VoA
  {singular: "laugh", plural: "laughs"}, // VoA
  {singular: "launch", plural: "launches"}, // VoA
  {singular: "law", plural: "laws"}, // VoA
  {singular: "lead", plural: "leads"}, // VoA
  {singular: "leak", plural: "leaks"}, // VoA
  {singular: "legislature", plural: "legislatures"}, // VoA
  {singular: "letter", plural: "letters"}, // VoA
  {singular: "level", plural: "levels"}, // VoA
  {singular: "liberal", plural: "liberals"}, // VoA
  {singular: "lie", plural: "lies"}, // VoA
  {singular: "life", plural: "lives"}, // VoA
  {singular: "lift", plural: "lifts"}, // VoA
  {singular: "light", plural: "lights"}, // VoA
  {singular: "like", plural: "likes"}, // VoA
  {singular: "limit", plural: "limits"}, // VoA
  {singular: "line", plural: "lines"}, // VoA
  {singular: "link", plural: "links"}, // VoA
  {singular: "liquid", plural: "liquids"}, // VoA
  {singular: "list", plural: "lists"}, // VoA
  {singular: "load", plural: "loads"}, // VoA
  {singular: "loan", plural: "loans"}, // VoA
  {singular: "local", plural: "locals"}, // VoA
  {singular: "look", plural: "looks"}, // VoA
  {singular: "love", plural: "loves"}, // VoA
  {singular: "low", plural: "lows"}, // VoA
  {singular: "machine", plural: "machines"}, // VoA
  {singular: "magazine", plural: "magazines"}, // VoA
  {singular: "major", plural: "majors"}, // VoA
  {singular: "majority", plural: "majorities"}, // VoA
  {singular: "make", plural: "makes"}, // VoA
  {singular: "male", plural: "males"}, // VoA
  {singular: "man", plural: "men"}, // VoA
  {singular: "map", plural: "maps"}, // VoA
  {singular: "march", plural: "marches"}, // VoA
  {singular: "mark", plural: "marks"}, // VoA
  {singular: "market", plural: "markets"}, // VoA
  {singular: "mass", plural: "masses"}, // VoA
  {singular: "mate", plural: "mates"}, // VoA
  {singular: "material", plural: "materials"}, // VoA
  {singular: "matter", plural: "matters"}, // VoA
  {singular: "mayor", plural: "mayors"}, // VoA
  {singular: "meal", plural: "meals"}, // VoA
  {singular: "mean", plural: "means"}, // VoA
  {singular: "measure", plural: "measures"}, // VoA
  {singular: "meat", plural: "meats"}, // VoA
  {singular: "medium", plural: "media"}, // VoA
  {singular: "medicine", plural: "medicines"}, // VoA
  {singular: "meet", plural: "meets"}, // VoA
  {singular: "member", plural: "members"}, // VoA
  {singular: "memorial", plural: "memorials"}, // VoA
  {singular: "memory", plural: "memories"}, // VoA
  {singular: "message", plural: "messages"}, // VoA
  {singular: "metal", plural: "metals"}, // VoA
  {singular: "method", plural: "methods"}, // VoA
  {singular: "microscope", plural: "microscopes"}, // VoA
  {singular: "military", plural: "militaries"}, // VoA
  {singular: "mind", plural: "minds"}, // VoA
  {singular: "mine", plural: "mines"}, // VoA
  {singular: "mineral", plural: "minerals"}, // VoA
  {singular: "minister", plural: "ministers"}, // VoA
  {singular: "minor", plural: "minors"}, // VoA
  {singular: "minority", plural: "minorities"}, // VoA
  {singular: "minute", plural: "minutes"}, // VoA
  {singular: "miss", plural: "misses"}, // VoA
  {singular: "missile", plural: "missiles"}, // VoA
  {singular: "mistake", plural: "mistakes"}, // VoA
  {singular: "mix", plural: "mixes"}, // VoA
  {singular: "mob", plural: "mobs"}, // VoA
  {singular: "model", plural: "models"}, // VoA
  {singular: "moderate", plural: "moderates"}, // VoA
  {singular: "month", plural: "months"}, // VoA
  {singular: "moon", plural: "moons"}, // VoA
  {singular: "moral", plural: "morals"}, // VoA
  {singular: "morning", plural: "mornings"}, // VoA
  {singular: "mother", plural: "mothers"}, // VoA
  {singular: "motion", plural: "motions"}, // VoA
  {singular: "mountain", plural: "mountains"}, // VoA
  {singular: "move", plural: "moves"}, // VoA
  {singular: "movement", plural: "movements"}, // VoA
  {singular: "movie", plural: "movies"}, // VoA
  {singular: "murder", plural: "murders"}, // VoA
  {singular: "mystery", plural: "mysteries"}, // VoA
  {singular: "name", plural: "names"}, // VoA
  {singular: "nation", plural: "nations"}, // VoA
  {singular: "native", plural: "natives"}, // VoA
  {singular: "navy", plural: "navies"}, // VoA
  {singular: "need", plural: "needs"}, // VoA
  {singular: "night", plural: "nights"}, // VoA
  {singular: "noise", plural: "noises"}, // VoA
  {singular: "normal", plural: "normals"}, // VoA
  {singular: "note", plural: "notes"}, // VoA
  {singular: "nothing", plural: "nothings"}, // VoA
  {singular: "number", plural: "numbers"}, // VoA
  {singular: "object", plural: "objects"}, // VoA
  {singular: "ocean", plural: "oceans"}, // VoA
  {singular: "offer", plural: "offers"}, // VoA
  {singular: "office", plural: "offices"}, // VoA
  {singular: "officer", plural: "officers"}, // VoA
  {singular: "oil", plural: "oils"}, // VoA
  {singular: "opinion", plural: "opinions"}, // VoA
  {singular: "opposite", plural: "opposites"}, // VoA
  {singular: "orbit", plural: "orbits"}, // VoA
  {singular: "order", plural: "orders"}, // VoA
  {singular: "other", plural: "others"}, // VoA
  {singular: "out", plural: "outs"}, // VoA
  {singular: "pain", plural: "pains"}, // VoA
  {singular: "paint", plural: "paints"}, // VoA
  {singular: "pan", plural: "pans"}, // VoA
  {singular: "paper", plural: "papers"}, // VoA
  {singular: "parachute", plural: "parachutes"}, // VoA
  {singular: "parade", plural: "parades"}, // VoA
  {singular: "pardon", plural: "pardons"}, // VoA
  {singular: "parent", plural: "parents"}, // VoA
  {singular: "parliament", plural: "parliaments"}, // VoA
  {singular: "part", plural: "parts"}, // VoA
  {singular: "party", plural: "parties"}, // VoA
  {singular: "pass", plural: "passes"}, // VoA
  {singular: "passenger", plural: "passengers"}, // VoA
  {singular: "passport", plural: "passports"}, // VoA
  {singular: "past", plural: "pasts"}, // VoA
  {singular: "path", plural: "paths"}, // VoA
  {singular: "patient", plural: "patients"}, // VoA
  {singular: "peace", plural: "peaces"}, // VoA
  {singular: "percent", plural: "percent"}, // VoA
  {singular: "period", plural: "periods"}, // VoA
  {singular: "permit", plural: "permits"}, // VoA
  {singular: "person", plural: "people"}, // VoA
  {singular: "physical", plural: "physicals"}, // VoA
  {singular: "picture", plural: "pictures"}, // VoA
  {singular: "piece", plural: "pieces"}, // VoA
  {singular: "pig", plural: "pigs"}, // VoA
  {singular: "pilot", plural: "pilots"}, // VoA
  {singular: "pipe", plural: "pipes"}, // VoA
  {singular: "place", plural: "places"}, // VoA
  {singular: "plan", plural: "plans"}, // VoA
  {singular: "planet", plural: "planets"}, // VoA
  {singular: "plant", plural: "plants"}, // VoA
  {singular: "plastic", plural: "plastics"}, // VoA
  {singular: "play", plural: "plays"}, // VoA
  {singular: "plot", plural: "plots"}, // VoA
  {singular: "poem", plural: "poems"}, // VoA
  {singular: "point", plural: "points"}, // VoA
  {singular: "poison", plural: "poisons"}, // VoA
  {singular: "policy", plural: "policies"}, // VoA
  {singular: "population", plural: "populations"}, // VoA
  {singular: "port", plural: "ports"}, // VoA
  {singular: "position", plural: "positions"}, // VoA
  {singular: "pour", plural: "pours"}, // VoA
  {singular: "power", plural: "powers"}, // VoA
  {singular: "praise", plural: "praises"}, // VoA
  {singular: "present", plural: "presents"}, // VoA
  {singular: "president", plural: "presidents"}, // VoA
  {singular: "press", plural: "presses"}, // VoA
  {singular: "pressure", plural: "pressures"}, // VoA
  {singular: "price", plural: "prices"}, // VoA
  {singular: "prison", plural: "prisons"}, // VoA
  {singular: "private", plural: "privates"}, // VoA
  {singular: "prize", plural: "prizes"}, // VoA
  {singular: "problem", plural: "problems"}, // VoA
  {singular: "process", plural: "processes"}, // VoA
  {singular: "profession", plural: "professions"}, // VoA
  {singular: "professor", plural: "professors"}, // VoA
  {singular: "profit", plural: "profits"}, // VoA
  {singular: "program", plural: "programs"}, // VoA
  {singular: "project", plural: "projects"}, // VoA
  {singular: "property", plural: "properties"}, // VoA
  {singular: "protest", plural: "protests"}, // VoA
  {singular: "publication", plural: "publications"}, // VoA
  {singular: "pull", plural: "pulls"}, // VoA
  {singular: "pump", plural: "pumps"}, // VoA
  {singular: "purchase", plural: "purchases"}, // VoA
  {singular: "purpose", plural: "purposes"}, // VoA
  {singular: "push", plural: "pushes"}, // VoA
  {singular: "quality", plural: "qualities"}, // VoA
  {singular: "question", plural: "questions"}, // VoA
  {singular: "race", plural: "races"}, // VoA
  {singular: "radio", plural: "radios"}, // VoA
  {singular: "raid", plural: "raids"}, // VoA
  {singular: "railroad", plural: "railroads"}, // VoA
  {singular: "rain", plural: "rains"}, // VoA
  {singular: "raise", plural: "raises"}, // VoA
  {singular: "rate", plural: "rates"}, // VoA
  {singular: "reach", plural: "reaches"}, // VoA
  {singular: "reason", plural: "reasons"}, // VoA
  {singular: "rebel", plural: "rebels"}, // VoA
  {singular: "recession", plural: "recessions"}, // VoA
  {singular: "record", plural: "records"}, // VoA
  {singular: "reform", plural: "reforms"}, // VoA
  {singular: "refugee", plural: "refugees"}, // VoA
  {singular: "regret", plural: "regrets"}, // VoA
  {singular: "reject", plural: "rejects"}, // VoA
  {singular: "relation", plural: "relations"}, // VoA
  {singular: "release", plural: "releases"}, // VoA
  {singular: "religion", plural: "religions"}, // VoA
  {singular: "repeat", plural: "repeats"}, // VoA
  {singular: "report", plural: "reports"}, // VoA
  {singular: "request", plural: "requests"}, // VoA
  {singular: "rescue", plural: "rescues"}, // VoA
  {singular: "resolution", plural: "resolutions"}, // VoA
  {singular: "resource", plural: "resources"}, // VoA
  {singular: "rest", plural: "rests"}, // VoA
  {singular: "result", plural: "results"}, // VoA
  {singular: "revolt", plural: "revolts"}, // VoA
  {singular: "ride", plural: "rides"}, // VoA
  {singular: "right", plural: "rights"}, // VoA
  {singular: "riot", plural: "riots"}, // VoA
  {singular: "risk", plural: "risks"}, // VoA
  {singular: "river", plural: "rivers"}, // VoA
  {singular: "road", plural: "roads"}, // VoA
  {singular: "rock", plural: "rocks"}, // VoA
  {singular: "rocket", plural: "rockets"}, // VoA
  {singular: "roll", plural: "rolls"}, // VoA
  {singular: "room", plural: "rooms"}, // VoA
  {singular: "root", plural: "roots"}, // VoA
  {singular: "rope", plural: "ropes"}, // VoA
  {singular: "rough", plural: "roughs"}, // VoA
  {singular: "round", plural: "rounds"}, // VoA
  {singular: "rub", plural: "rubs"}, // VoA
  {singular: "ruin", plural: "ruins"}, // VoA
  {singular: "rule", plural: "rules"}, // VoA
  {singular: "run", plural: "runs"}, // VoA
  {singular: "sabotage", plural: "sabotages"}, // VoA
  {singular: "sacrifice", plural: "sacrifices"}, // VoA
  {singular: "safe", plural: "safes"}, // VoA
  {singular: "sail", plural: "sails"}, // VoA
  {singular: "sailor", plural: "sailors"}, // VoA
  {singular: "salt", plural: "salts"}, // VoA
  {singular: "sand", plural: "sands"}, // VoA
  {singular: "satellite", plural: "satellites"}, // VoA
  {singular: "school", plural: "schools"}, // VoA
  {singular: "science", plural: "sciences"}, // VoA
  {singular: "sea", plural: "seas"}, // VoA
  {singular: "search", plural: "searches"}, // VoA
  {singular: "season", plural: "seasons"}, // VoA
  {singular: "seat", plural: "seats"}, // VoA
  {singular: "second", plural: "seconds"}, // VoA
  {singular: "secret", plural: "secrets"}, // VoA
  {singular: "security", plural: "securities"}, // VoA
  {singular: "seed", plural: "seeds"}, // VoA
  {singular: "self", plural: "selves"}, // VoA
  {singular: "sense", plural: "senses"}, // VoA
  {singular: "sentence", plural: "sentences"}, // VoA
  {singular: "series", plural: "series"}, // VoA
  {singular: "service", plural: "services"}, // VoA
  {singular: "set", plural: "sets"}, // VoA
  {singular: "sex", plural: "sexes"}, // VoA
  {singular: "shake", plural: "shakes"}, // VoA
  {singular: "shape", plural: "shapes"}, // VoA
  {singular: "share", plural: "shares"}, // VoA
  {singular: "sheep", plural: "sheeps"}, // VoA
  {singular: "shell", plural: "shells"}, // VoA
  {singular: "shelter", plural: "shelters"}, // VoA
  {singular: "shine", plural: "shines"}, // VoA
  {singular: "ship", plural: "ships"}, // VoA
  {singular: "shock", plural: "shocks"}, // VoA
  {singular: "shoe", plural: "shoes"}, // VoA
  {singular: "shoot", plural: "shoots"}, // VoA
  {singular: "short", plural: "shorts"}, // VoA
  {singular: "shout", plural: "shouts"}, // VoA
  {singular: "show", plural: "shows"}, // VoA
  {singular: "sickness", plural: "sicknesses"}, // VoA
  {singular: "side", plural: "sides"}, // VoA
  {singular: "sign", plural: "signs"}, // VoA
  {singular: "signal", plural: "signals"}, // VoA
  {singular: "silence", plural: "silences"}, // VoA
  {singular: "silver", plural: "silvers"}, // VoA
  {singular: "sink", plural: "sinks"}, // VoA
  {singular: "sister", plural: "sisters"}, // VoA
  {singular: "situation", plural: "situations"}, // VoA
  {singular: "size", plural: "sizes"}, // VoA
  {singular: "skeleton", plural: "skeletons"}, // VoA
  {singular: "skill", plural: "skills"}, // VoA
  {singular: "skin", plural: "skins"}, // VoA
  {singular: "sky", plural: "skies"}, // VoA
  {singular: "slave", plural: "slaves"}, // VoA
  {singular: "sleep", plural: "sleeps"}, // VoA
  {singular: "slide", plural: "slides"}, // VoA
  {singular: "smell", plural: "smells"}, // VoA
  {singular: "smoke", plural: "smokes"}, // VoA
  {singular: "snow", plural: "snows"}, // VoA
  {singular: "social", plural: "socials"}, // VoA
  {singular: "soldier", plural: "soldiers"}, // VoA
  {singular: "solid", plural: "solids"}, // VoA
  {singular: "son", plural: "sons"}, // VoA
  {singular: "sort", plural: "sorts"}, // VoA
  {singular: "sound", plural: "sounds"}, // VoA
  {singular: "south", plural: "souths"}, // VoA
  {singular: "space", plural: "spaces"}, // VoA
  {singular: "special", plural: "specials"}, // VoA
  {singular: "speech", plural: "speeches"}, // VoA
  {singular: "spend", plural: "spends"}, // VoA
  {singular: "spill", plural: "spills"}, // VoA
  {singular: "spirit", plural: "spirits"}, // VoA
  {singular: "split", plural: "splits"}, // VoA
  {singular: "sport", plural: "sports"}, // VoA
  {singular: "spread", plural: "spreads"}, // VoA
  {singular: "spring", plural: "springs"}, // VoA
  {singular: "spy", plural: "spies"}, // VoA
  {singular: "square", plural: "squares"}, // VoA
  {singular: "stab", plural: "stabs"}, // VoA
  {singular: "stand", plural: "stands"}, // VoA
  {singular: "star", plural: "stars"}, // VoA
  {singular: "start", plural: "starts"}, // VoA
  {singular: "state", plural: "states"}, // VoA
  {singular: "station", plural: "stations"}, // VoA
  {singular: "statue", plural: "statues"}, // VoA
  {singular: "stay", plural: "stays"}, // VoA
  {singular: "steam", plural: "steams"}, // VoA
  {singular: "steel", plural: "steels"}, // VoA
  {singular: "step", plural: "steps"}, // VoA
  {singular: "stick", plural: "sticks"}, // VoA
  {singular: "still", plural: "stills"}, // VoA
  {singular: "stone", plural: "stones"}, // VoA
  {singular: "stop", plural: "stops"}, // VoA
  {singular: "store", plural: "stores"}, // VoA
  {singular: "storm", plural: "storms"}, // VoA
  {singular: "story", plural: "stories"}, // VoA
  {singular: "stove", plural: "stoves"}, // VoA
  {singular: "street", plural: "streets"}, // VoA
  {singular: "stretch", plural: "stretches"}, // VoA
  {singular: "strike", plural: "strikes"}, // VoA
  {singular: "structure", plural: "structures"}, // VoA
  {singular: "struggle", plural: "struggles"}, // VoA
  {singular: "study", plural: "studies"}, // VoA
  {singular: "subject", plural: "subjects"}, // VoA
  {singular: "submarine", plural: "submarines"}, // VoA
  {singular: "substance", plural: "substances"}, // VoA
  {singular: "substitute", plural: "substitutes"}, // VoA
  {singular: "sugar", plural: "sugars"}, // VoA
  {singular: "summer", plural: "summers"}, // VoA
  {singular: "sun", plural: "suns"}, // VoA
  {singular: "supply", plural: "supplies"}, // VoA
  {singular: "support", plural: "supports"}, // VoA
  {singular: "surface", plural: "surfaces"}, // VoA
  {singular: "surplus", plural: "surpluses"}, // VoA
  {singular: "surprise", plural: "surprises"}, // VoA
  {singular: "surrender", plural: "surrenders"}, // VoA
  {singular: "suspect", plural: "suspects"}, // VoA
  {singular: "swallow", plural: "swallows"}, // VoA
  {singular: "swim", plural: "swims"}, // VoA
  {singular: "sympathy", plural: "sympathies"}, // VoA
  {singular: "system", plural: "systems"}, // VoA
  {singular: "take", plural: "takes"}, // VoA
  {singular: "talk", plural: "talks"}, // VoA
  {singular: "tank", plural: "tanks"}, // VoA
  {singular: "target", plural: "targets"}, // VoA
  {singular: "taste", plural: "tastes"}, // VoA
  {singular: "tax", plural: "taxes"}, // VoA
  {singular: "tea", plural: "teas"}, // VoA
  {singular: "team", plural: "teams"}, // VoA
  {singular: "tear", plural: "tears"}, // VoA
  {singular: "technology", plural: "technologies"}, // VoA
  {singular: "telephone", plural: "telephones"}, // VoA
  {singular: "telescope", plural: "telescopes"}, // VoA
  {singular: "television", plural: "televisions"}, // VoA
  {singular: "temperature", plural: "temperatures"}, // VoA
  {singular: "tense", plural: "tenses"}, // VoA
  {singular: "term", plural: "terms"}, // VoA
  {singular: "territory", plural: "territories"}, // VoA
  {singular: "terror", plural: "terrors"}, // VoA
  {singular: "terrorist", plural: "terrorists"}, // VoA
  {singular: "test", plural: "tests"}, // VoA
  {singular: "theater", plural: "theaters"}, // VoA
  {singular: "theory", plural: "theories"}, // VoA
  {singular: "thing", plural: "things"}, // VoA
  {singular: "third", plural: "thirds"}, // VoA
  {singular: "throw", plural: "throws"}, // VoA
  {singular: "tie", plural: "ties"}, // VoA
  {singular: "time", plural: "times"}, // VoA
  {singular: "tool", plural: "tools"}, // VoA
  {singular: "top", plural: "tops"}, // VoA
  {singular: "torture", plural: "tortures"}, // VoA
  {singular: "total", plural: "totals"}, // VoA
  {singular: "touch", plural: "touches"}, // VoA
  {singular: "town", plural: "towns"}, // VoA
  {singular: "trade", plural: "trades"}, // VoA
  {singular: "tradition", plural: "traditions"}, // VoA
  {singular: "train", plural: "trains"}, // VoA
  {singular: "transportation", plural: "transportations"}, // VoA
  {singular: "trap", plural: "traps"}, // VoA
  {singular: "travel", plural: "travels"}, // VoA
  {singular: "treason", plural: "treasons"}, // VoA
  {singular: "treasure", plural: "treasures"}, // VoA
  {singular: "treat", plural: "treats"}, // VoA
  {singular: "treatment", plural: "treatments"}, // VoA
  {singular: "treaty", plural: "treaties"}, // VoA
  {singular: "tree", plural: "trees"}, // VoA
  {singular: "trial", plural: "trials"}, // VoA
  {singular: "tribe", plural: "tribes"}, // VoA
  {singular: "trick", plural: "tricks"}, // VoA
  {singular: "trip", plural: "trips"}, // VoA
  {singular: "troop", plural: "troops"}, // VoA
  {singular: "trouble", plural: "troubles"}, // VoA
  {singular: "truck", plural: "trucks"}, // VoA
  {singular: "trust", plural: "trusts"}, // VoA
  {singular: "try", plural: "tries"}, // VoA
  {singular: "tube", plural: "tubes"}, // VoA
  {singular: "turn", plural: "turns"}, // VoA
  {singular: "universe", plural: "universes"}, // VoA
  {singular: "university", plural: "universities"}, // VoA
  {singular: "urge", plural: "urges"}, // VoA
  {singular: "use", plural: "uses"}, // VoA
  {singular: "valley", plural: "valleys"}, // VoA
  {singular: "value", plural: "values"}, // VoA
  {singular: "vegetable", plural: "vegetables"}, // VoA
  {singular: "vehicle", plural: "vehicles"}, // VoA
  {singular: "version", plural: "versions"}, // VoA
  {singular: "veto", plural: "vetoes"}, // VoA
  {singular: "victim", plural: "victims"}, // VoA
  {singular: "victory", plural: "victories"}, // VoA
  {singular: "village", plural: "villages"}, // VoA
  {singular: "visit", plural: "visits"}, // VoA
  {singular: "voice", plural: "voices"}, // VoA
  {singular: "volcano", plural: "volcanoes"}, // VoA
  {singular: "vote", plural: "votes"}, // VoA
  {singular: "wage", plural: "wages"}, // VoA
  {singular: "wait", plural: "waits"}, // VoA
  {singular: "walk", plural: "walks"}, // VoA
  {singular: "wall", plural: "walls"}, // VoA
  {singular: "want", plural: "wants"}, // VoA
  {singular: "war", plural: "wars"}, // VoA
  {singular: "wash", plural: "washes"}, // VoA
  {singular: "waste", plural: "wastes"}, // VoA
  {singular: "watch", plural: "watches"}, // VoA
  {singular: "water", plural: "waters"}, // VoA
  {singular: "wave", plural: "waves"}, // VoA
  {singular: "way", plural: "ways"}, // VoA
  {singular: "weapon", plural: "weapons"}, // VoA
  {singular: "week", plural: "weeks"}, // VoA
  {singular: "wheel", plural: "wheels"}, // VoA
  {singular: "whole", plural: "wholes"}, // VoA
  {singular: "wife", plural: "wives"}, // VoA
  {singular: "will", plural: "wills"}, // VoA
  {singular: "win", plural: "wins"}, // VoA
  {singular: "wind", plural: "winds"}, // VoA
  {singular: "window", plural: "windows"}, // VoA
  {singular: "winter", plural: "winters"}, // VoA
  {singular: "wire", plural: "wires"}, // VoA
  {singular: "wish", plural: "wishes"}, // VoA
  {singular: "woman", plural: "women"}, // VoA
  {singular: "wonder", plural: "wonders"}, // VoA
  {singular: "wood", plural: "woods"}, // VoA
  {singular: "word", plural: "words"}, // VoA
  {singular: "work", plural: "works"}, // VoA
  {singular: "world", plural: "worlds"}, // VoA
  {singular: "worry", plural: "worries"}, // VoA
  {singular: "wound", plural: "wounds"}, // VoA
  {singular: "wreck", plural: "wrecks"}, // VoA
  {singular: "wreckage", plural: "wreckages"}, // VoA
  {singular: "wrong", plural: "wrongs"}, // VoA
  {singular: "year", plural: "years"}, // VoA
  {singular: "zero", plural: "zeroes"}, // VoA
  {singular: "zoo", plural: "zoos"}, // VoA
  {singular: "atom", plural: "atoms"}, // VoA
  {singular: "bacterium", plural: "bacteria"}, // VoA
  {singular: "cell", plural: "cells"}, // VoA
  {singular: "chromosome", plural: "chromosomes"}, // VoA
  {singular: "compound", plural: "compounds"}, // VoA
  {singular: "electron", plural: "electrons"}, // VoA
  {singular: "element", plural: "elements"}, // VoA
  {singular: "enzyme", plural: "enzymes"}, // VoA
  {singular: "fetus", plural: "fetuses"}, // VoA
  {singular: "fission", plural: "fissions"}, // VoA
  {singular: "fusion", plural: "fusions"}, // VoA
  {singular: "gene", plural: "genes"}, // VoA
  {singular: "gravity", plural: "gravities"}, // VoA
  {singular: "image", plural: "images"}, // VoA
  {singular: "laser", plural: "lasers"}, // VoA
  {singular: "magnet", plural: "magnets"}, // VoA
  {singular: "molecule", plural: "molecules"}, // VoA
  {singular: "nerve", plural: "nerves"}, // VoA
  {singular: "nucleus", plural: "nuclei"}, // VoA
  {singular: "nutrient", plural: "nutrients"}, // VoA
  {singular: "organ", plural: "organs"}, // VoA
  {singular: "organism", plural: "organisms"}, // VoA
  {singular: "particle", plural: "particles"}, // VoA
  {singular: "protein", plural: "proteins"}, // VoA
  {singular: "robot", plural: "robots"}, // VoA
  {singular: "tissue", plural: "tissues"}, // VoA
  {singular: "virus", plural: "viruses"}, // VoA
  {singular: "x-ray", plural: "x-rays"}, // VoA
  {singular: "heart", plural: "hearts"}, // VoA
  {singular: "intestine", plural: "intestines"}, // VoA
  {singular: "kidney", plural: "kidneys"}, // VoA
  {singular: "liver", plural: "livers"}, // VoA
  {singular: "lung", plural: "lungs"}, // VoA
  {singular: "prostate", plural: "prostates"}, // VoA
  {singular: "stomach", plural: "stomachs"}, // VoA
  {singular: "uterus", plural: "uteruses"}, // VoA
];

const BITS = maxBitsForList(COUNT_NOUNS_ALL);
const COUNT_NOUNS = takeNBitsBestItemsOf(COUNT_NOUNS_ALL, BITS, (cn) => cn.plural.length);

export class CountNounBank implements IWordbank {
  bits() {
    return BITS;
  }

  getEntry(i: number, qty?: number) {
    const substruct = COUNT_NOUNS[i];
    return (qty && qty > 1) ? substruct.plural : substruct.singular;
  }
}