// https://en.wikipedia.org/wiki/Part_of_speech
const IS_NOUN = 1;
const IS_VERB = 2;
const IS_ADJECTIVE = 4;
const IS_ADVERB = 8;
const IS_PREPOSITION = 16;
const IS_CONJUNCTION = 32;
const IS_DETERMINER = 64;

const VOA_MAP = {
  "a": IS_DETERMINER,
  "able": IS_VERB | IS_ADJECTIVE,
  "about": IS_ADVERB | IS_ADJECTIVE | IS_PREPOSITION,
  "above": IS_ADVERB | IS_PREPOSITION,
  "accept": IS_VERB,
  "accident": IS_NOUN,
  "accuse": IS_VERB,
  "across": IS_ADVERB | IS_PREPOSITION,
  "act": IS_NOUN | IS_VERB,
  "activist": IS_NOUN,
  "actor": IS_NOUN,
  "add": IS_VERB,
  "administration": IS_NOUN,
  "admit": IS_VERB | IS_NOUN,
  "adult": IS_ADJECTIVE | IS_NOUN,
  "advise": IS_VERB,
  "affect": IS_VERB,
  "afraid": IS_ADJECTIVE,
  "after": IS_ADVERB | IS_PREPOSITION,
  "again": IS_ADVERB,
  "against": IS_PREPOSITION,
  "age": IS_VERB | IS_NOUN,
  "agency": IS_NOUN,
  "aggression": IS_NOUN,
  "ago": IS_ADJECTIVE | IS_ADVERB,
  "agree": IS_VERB,
  "agriculture": IS_NOUN,
  "aid": IS_VERB | IS_NOUN,
  "aim": IS_VERB | IS_NOUN,
  "air": IS_VERB | IS_NOUN,
  "airplane": IS_NOUN,
  "airport": IS_NOUN,
  "album": IS_NOUN,
  "alcohol": IS_NOUN,
  "alive": IS_ADJECTIVE,
  "all": IS_DETERMINER | IS_ADVERB,
  "ally": IS_NOUN | IS_VERB,
  "almost": IS_ADVERB,
  "alone": IS_ADJECTIVE | IS_ADVERB,
  "along": IS_PREPOSITION | IS_ADVERB,
  "already": IS_ADVERB,
  "also": IS_ADVERB,
  "although": IS_CONJUNCTION,
  "always": IS_ADVERB,
  "ambassador": IS_NOUN,
  "amend": IS_VERB,
  "ammunition": IS_NOUN,
  "among": IS_PREPOSITION,
  "amount": IS_NOUN,
  "anarchy": IS_NOUN,
  "ancestor": IS_NOUN,
  "ancient": IS_ADJECTIVE,
  "and": IS_CONJUNCTION,
  "anger": IS_NOUN | IS_VERB,
  "animal": IS_NOUN | IS_VERB,
  "anniversary": IS_NOUN,
  "announce": IS_VERB,
  "another": IS_DETERMINER,
  "answer": IS_NOUN | IS_VERB,
  "any": IS_ADVERB | IS_DETERMINER,
  "apologize": IS_VERB,
  "appeal": IS_VERB | IS_NOUN,
  "appear": IS_VERB,
  "appoint": IS_VERB,
  "approve": IS_VERB,
  "archeology": IS_NOUN,
  "area": IS_NOUN,
  "argue": IS_VERB,
  "arms": IS_NOUN,
  "army": IS_NOUN,
  "around": IS_PREPOSITION,
  "arrest": IS_NOUN | IS_VERB,
  "arrive": IS_VERB,
  "art": IS_NOUN,
  "artillery": IS_NOUN,
  "as": IS_ADVERB | IS_CONJUNCTION | IS_PREPOSITION,
  "ash": IS_NOUN,
  "ask": IS_VERB | IS_NOUN,
  "assist": IS_VERB | IS_NOUN,
  "astronaut": IS_NOUN,
  "astronomy": IS_NOUN,
  "asylum": IS_NOUN,
  "at": IS_PREPOSITION,
  "atmosphere": IS_NOUN,
  "attach": IS_VERB,
  "attack": IS_NOUN | IS_VERB,
  "attempt": IS_NOUN | IS_VERB,
  "attend": IS_VERB,
  "automobile": IS_NOUN,
  "autumn": IS_NOUN,
  "average": IS_NOUN | IS_VERB,
  "avoid": IS_VERB,
  "awake": IS_ADJECTIVE,
  "award": IS_VERB | IS_NOUN,
  "away": IS_ADVERB,
  "baby": IS_NOUN | IS_ADJECTIVE,
  "back": IS_ADJECTIVE | IS_ADVERB,
  "bad": IS_ADJECTIVE | IS_ADVERB,
  "balance": IS_NOUN | IS_VERB,
  "ball": IS_NOUN,
  "balloon": IS_NOUN,
  "ballot": IS_NOUN,
  "ban": IS_NOUN | IS_VERB,
  "bank": IS_NOUN | IS_VERB,
  "bar": IS_NOUN | IS_VERB,
  "barrier": IS_NOUN,
  "base": IS_NOUN | IS_VERB,
  "battle": IS_NOUN | IS_VERB,
  "be": IS_VERB,
  "beat": IS_NOUN | IS_VERB,
  "beauty": IS_NOUN,
  "because": IS_ADVERB | IS_CONJUNCTION,
  "become": IS_VERB,
  "bed": IS_NOUN,
  "before": IS_PREPOSITION | IS_ADVERB | IS_CONJUNCTION,
  "begin": IS_VERB,
  "behind": IS_PREPOSITION | IS_ADVERB | IS_NOUN,
  "believe": IS_VERB,
  "bell": IS_NOUN,
  "belong": IS_VERB,
  "below": IS_PREPOSITION | IS_ADVERB,
  "best": IS_ADJECTIVE | IS_ADVERB | IS_NOUN | IS_VERB,
  "betray": IS_VERB,
  "better": IS_ADJECTIVE | IS_ADVERB | IS_NOUN,
  "between": IS_PREPOSITION,
  "big": IS_ADJECTIVE | IS_ADVERB,
  "bill": IS_VERB | IS_NOUN,
  "biology": IS_NOUN,
  "bird": IS_NOUN,
  "bite": IS_NOUN | IS_VERB,
  "black": IS_ADJECTIVE | IS_NOUN,
  "blame": IS_NOUN | IS_VERB,
  "blanket": IS_NOUN,
  "bleed": IS_VERB,
  "blind": IS_NOUN | IS_VERB,
  "block": IS_NOUN | IS_VERB,
  "blood": IS_NOUN,
  "blow": IS_NOUN | IS_VERB,
  "blue": IS_ADJECTIVE | IS_NOUN,
  "boat": IS_NOUN,
  "body": IS_NOUN,
  "boil": IS_NOUN | IS_VERB,
  "bomb": IS_NOUN | IS_VERB,
  "bone": IS_NOUN,
  "book": IS_NOUN | IS_VERB,
  "border": IS_NOUN | IS_VERB,
  "born": IS_VERB | IS_ADJECTIVE,
  "borrow": IS_VERB,
  "both": IS_DETERMINER | IS_CONJUNCTION,
  "bottle": IS_NOUN | IS_VERB,
  "bottom": IS_NOUN | IS_ADJECTIVE,
  "box": IS_NOUN | IS_VERB,
  "boy": IS_NOUN,
  "boycott": IS_NOUN | IS_VERB,
  "brain": IS_NOUN,
  "brave": IS_ADJECTIVE | IS_VERB,
  "bread": IS_NOUN,
  "break": IS_NOUN | IS_VERB,
  "breathe": IS_VERB,
  "bridge": IS_NOUN | IS_VERB,
  "brief": IS_NOUN | IS_ADJECTIVE | IS_VERB,
  "bright": IS_ADJECTIVE,
  "bring": IS_VERB,
  "broadcast": IS_VERB | IS_NOUN,
  "brother": IS_NOUN,
  "brown": IS_NOUN | IS_ADJECTIVE | IS_VERB,
  "budget": IS_NOUN,
  "build": IS_VERB | IS_NOUN,
  "building": IS_NOUN,
  "bullet": IS_NOUN,
  "burn": IS_NOUN | IS_VERB,
  "burst": IS_NOUN | IS_VERB,
  "bury": IS_VERB,
  "bus": IS_NOUN | IS_VERB,
  "business": IS_NOUN,
  "busy": IS_ADJECTIVE | IS_VERB,
  "but": IS_PREPOSITION | IS_ADVERB | IS_CONJUNCTION,
  "buy": IS_VERB,
  "by": IS_PREPOSITION | IS_ADVERB | IS_ADJECTIVE,
  "cabinet": IS_NOUN,
  "call": IS_NOUN | IS_VERB,
  "calm": IS_ADJECTIVE | IS_NOUN | IS_VERB,
  "camera": IS_NOUN,
  "camp": IS_NOUN | IS_VERB,
  "campaign": IS_VERB | IS_NOUN,
  "can": IS_NOUN | IS_VERB,
  "cancel": IS_VERB,
  "cancer": IS_NOUN,
  "candidate": IS_NOUN,
  "capital": IS_NOUN,
  "capitalism": IS_NOUN,
  "capture": IS_NOUN | IS_VERB,
  "car": IS_NOUN,
  "care": IS_NOUN | IS_VERB,
  "careful": IS_ADJECTIVE,
  "carry": IS_VERB,
  "case": IS_VERB | IS_NOUN,
  "cat": IS_NOUN,
  "catch": IS_VERB | IS_NOUN,
  "cause": IS_NOUN | IS_VERB,
  "ceasefire": IS_NOUN,
  "celebrate": IS_VERB,
  "center": IS_NOUN | IS_ADJECTIVE | IS_VERB,
  "century": IS_NOUN,
  "ceremony": IS_NOUN,
  "chairman": IS_NOUN,
  "champion": IS_NOUN,
  "chance": IS_NOUN | IS_VERB,
  "change": IS_NOUN | IS_VERB,
  "charge": IS_NOUN | IS_VERB,
  "chase": IS_NOUN | IS_VERB,
  "cheat": IS_NOUN | IS_VERB,
  "cheer": IS_NOUN | IS_VERB,
  "chemical": IS_NOUN | IS_ADJECTIVE,
  "chemistry": IS_NOUN,
  "chief": IS_NOUN | IS_ADJECTIVE,
  "child": IS_NOUN,
  "children": IS_NOUN,
  "choose": IS_VERB,
  "circle": IS_NOUN | IS_VERB,
  "citizen": IS_NOUN,
  "city": IS_NOUN,
  "civilian": IS_NOUN,
  "claim": IS_NOUN | IS_VERB,
  "clash": IS_NOUN | IS_VERB,
  "clean": IS_ADJECTIVE | IS_VERB,
  "clear": IS_ADJECTIVE | IS_ADVERB | IS_VERB,
  "clergy": IS_NOUN,
  "climate": IS_NOUN,
  "climb": IS_NOUN | IS_VERB,
  "clock": IS_NOUN,
  "close": IS_VERB | IS_NOUN | IS_ADJECTIVE,
  "cloth": IS_NOUN,
  "clothes": IS_NOUN,
  "cloud": IS_NOUN,
  "coal": IS_NOUN,
  "coalition": IS_NOUN,
  "coast": IS_NOUN | IS_VERB,
  "coffee": IS_NOUN,
  "cold": IS_ADJECTIVE | IS_NOUN,
  "collect": IS_VERB,
  "college": IS_NOUN,
  "colony": IS_NOUN,
  "color": IS_NOUN | IS_VERB,
  "combine": IS_VERB,
  "come": IS_VERB,
  "command": IS_VERB | IS_NOUN,
  "comment": IS_VERB | IS_NOUN,
  "committee": IS_NOUN,
  "common": IS_ADJECTIVE,
  "communicate": IS_VERB,
  "community": IS_NOUN,
  "company": IS_NOUN,
  "compare": IS_VERB,
  "compete": IS_VERB,
  "complete": IS_VERB | IS_ADJECTIVE,
  "complex": IS_ADJECTIVE | IS_NOUN,
  "compromise": IS_VERB | IS_NOUN,
  "computer": IS_NOUN,
  "concern": IS_NOUN | IS_VERB,
  "condemn": IS_VERB,
  "condition": IS_NOUN | IS_VERB,
  "conference": IS_NOUN,
  "confirm": IS_VERB,
  "conflict": IS_NOUN,
  "congratulate": IS_VERB,
  "congress": IS_NOUN,
  "connect": IS_VERB,
  "conservative": IS_ADJECTIVE | IS_NOUN,
  "consider": IS_VERB,
  "constitution": IS_NOUN,
  "contain": IS_VERB,
  "container": IS_NOUN,
  "continent": IS_NOUN,
  "continue": IS_VERB,
  "control": IS_NOUN | IS_VERB,
  "convention": IS_NOUN,
  "cook": IS_NOUN | IS_VERB,
  "cool": IS_ADJECTIVE | IS_NOUN | IS_VERB,
  "cooperate": 0,
  "copy": 0,
  "corn": 0,
  "correct": 0,
  "cost": 0,
  "cotton": 0,
  "count": 0,
  "country": 0,
  "court": 0,
  "cover": 0,
  "cow": 0,
  "crash": 0,
  "create": 0,
  "creature": 0,
  "credit": 0,
  "crew": 0,
  "crime": 0,
  "criminal": 0,
  "crisis": 0,
  "criticize": 0,
  "crops": 0,
  "cross": 0,
  "crowd": 0,
  "crush": 0,
  "cry": 0,
  "culture": 0,
  "cure": 0,
  "curfew": 0,
  "current": 0,
  "custom": 0,
  "customs": 0,
  "cut": 0,
  "dam": 0,
  "damage": 0,
  "dance": 0,
  "danger": 0,
  "dark": 0,
  "date": 0,
  "daughter": 0,
  "day": 0,
  "dead": 0,
  "deaf": 0,
  "deal": 0,
  "debate": 0,
  "debt": 0,
  "decide": 0,
  "declare": 0,
  "decrease": 0,
  "deep": 0,
  "defeat": 0,
  "defend": 0,
  "deficit": 0,
  "define": 0,
  "degree": 0,
  "delay": 0,
  "delegate": 0,
  "demand": 0,
  "democracy": 0,
  "demonstrate": 0,
  "denounce": 0,
  "deny": 0,
  "depend": 0,
  "deplore": 0,
  "deploy": 0,
  "depression": 0,
  "describe": 0,
  "desert": 0,
  "design": 0,
  "desire": 0,
  "destroy": 0,
  "detail": 0,
  "develop": 0,
  "device": 0,
  "dictator": 0,
  "die": 0,
  "diet": 0,
  "different": 0,
  "difficult": 0,
  "dig": 0,
  "dinner": 0,
  "diplomat": 0,
  "direct": 0,
  "direction": 0,
  "dirt": 0,
  "disappear": 0,
  "disarm": 0,
  "discover": 0,
  "discuss": 0,
  "disease": 0,
  "dismiss": 0,
  "dispute": 0,
  "dissident": 0,
  "distance": 0,
  "dive": 0,
  "divide": 0,
  "do": 0,
  "doctor": 0,
  "document": 0,
  "dog": 0,
  "dollar": 0,
  "door": 0,
  "down": 0,
  "dream": 0,
  "drink": 0,
  "drive": 0,
  "drop": 0,
  "drown": 0,
  "drug": 0,
  "dry": 0,
  "during": 0,
  "dust": 0,
  "duty": 0,
  "each": 0,
  "early": IS_ADJECTIVE | IS_ADVERB,
  "earn": 0,
  "earth": 0,
  "earthquake": 0,
  "ease": 0,
  "east": 0,
  "easy": 0,
  "eat": 0,
  "ecology": 0,
  "economy": 0,
  "edge": 0,
  "education": 0,
  "effect": 0,
  "effort": 0,
  "egg": 0,
  "either": 0,
  "elect": 0,
  "electricity": 0,
  "embassy": 0,
  "emergency": 0,
  "emotion": 0,
  "employ": 0,
  "empty": 0,
  "end": 0,
  "enemy": 0,
  "energy": 0,
  "enforce": 0,
  "engine": 0,
  "engineer": 0,
  "enjoy": 0,
  "enough": 0,
  "enter": 0,
  "environment": 0,
  "equal": 0,
  "equipment": 0,
  "escape": 0,
  "especially": IS_ADVERB,
  "establish": 0,
  "estimate": 0,
  "ethnic": 0,
  "evaporate": 0,
  "even": 0,
  "event": 0,
  "ever": 0,
  "every": 0,
  "evidence": 0,
  "evil": 0,
  "exact": 0,
  "examine": 0,
  "example": 0,
  "excellent": 0,
  "except": 0,
  "exchange": 0,
  "excuse": 0,
  "execute": 0,
  "exercise": 0,
  "exile": 0,
  "exist": 0,
  "expand": 0,
  "expect": 0,
  "expel": 0,
  "experience": 0,
  "experiment": 0,
  "expert": 0,
  "explain": 0,
  "explode": 0,
  "explore": 0,
  "export": 0,
  "express": 0,
  "extend": 0,
  "extra": 0,
  "extreme": 0,
  "extremist": 0,
  "face": 0,
  "fact": 0,
  "factory": 0,
  "fail": 0,
  "fair": 0,
  "fall": 0,
  "false": 0,
  "family": 0,
  "famous": 0,
  "far": 0,
  "farm": 0,
  "fast": 0,
  "fat": 0,
  "father": 0,
  "fear": 0,
  "federal": 0,
  "feed": 0,
  "feel": 0,
  "female": 0,
  "fence": 0,
  "fertile": 0,
  "few": 0,
  "field": 0,
  "fierce": 0,
  "fight": 0,
  "fill": 0,
  "film": 0,
  "final": 0,
  "financial": 0,
  "find": 0,
  "fine": 0,
  "finish": 0,
  "fire": 0,
  "fireworks": 0,
  "firm": 0,
  "first": 0,
  "fish": 0,
  "fit": 0,
  "fix": 0,
  "flag": 0,
  "flat": 0,
  "flee": 0,
  "float": 0,
  "flood": 0,
  "floor": 0,
  "flow": 0,
  "flower": 0,
  "fluid": 0,
  "fly": 0,
  "fog": 0,
  "follow": 0,
  "food": 0,
  "fool": 0,
  "foot": 0,
  "for": IS_CONJUNCTION,
  "force": 0,
  "foreign": 0,
  "forest": 0,
  "forget": 0,
  "forgive": 0,
  "form": 0,
  "former": 0,
  "forward": 0,
  "free": 0,
  "freedom": 0,
  "freeze": 0,
  "fresh": 0,
  "friend": 0,
  "frighten": 0,
  "from": 0,
  "front": 0,
  "fruit": 0,
  "fuel": 0,
  "full": 0,
  "fun": 0,
  "funeral": 0,
  "future": 0,
  "gain": 0,
  "game": 0,
  "gas": 0,
  "gather": 0,
  "general": 0,
  "gentle": 0,
  "get": 0,
  "gift": 0,
  "girl": 0,
  "give": 0,
  "glass": 0,
  "go": 0,
  "goal": 0,
  "god": 0,
  "gold": 0,
  "good": 0,
  "goods": 0,
  "govern": 0,
  "government": 0,
  "grain": 0,
  "granddaughter": 0,
  "grandfather": 0,
  "grandmother": 0,
  "grandson": 0,
  "grass": 0,
  "gray": 0,
  "great": 0,
  "green": 0,
  "grind": 0,
  "ground": 0,
  "group": 0,
  "grow": 0,
  "guarantee": 0,
  "guard": 0,
  "guerrilla": 0,
  "guide": 0,
  "guilty": 0,
  "gun": 0,
  "hair": 0,
  "half": 0,
  "halt": 0,
  "hang": 0,
  "happen": 0,
  "happy": 0,
  "hard": 0,
  "harm": 0,
  "harvest": 0,
  "hat": 0,
  "hate": 0,
  "have": 0,
  "he": 0,
  "head": 0,
  "headquarters": 0,
  "heal": 0,
  "health": 0,
  "hear": 0,
  "heat": 0,
  "heavy": 0,
  "helicopter": 0,
  "help": 0,
  "here": IS_ADVERB | IS_NOUN | IS_ADJECTIVE,
  "hero": 0,
  "hide": 0,
  "high": 0,
  "hijack": 0,
  "hill": 0,
  "history": 0,
  "hit": 0,
  "hold": 0,
  "hole": 0,
  "holiday": 0,
  "holy": 0,
  "home": 0,
  "honest": 0,
  "honor": 0,
  "hope": 0,
  "horrible": 0,
  "horse": 0,
  "hospital": 0,
  "hostage": 0,
  "hostile": 0,
  "hot": 0,
  "hotel": 0,
  "hour": 0,
  "house": 0,
  "how": 0,
  "however": 0,
  "huge": 0,
  "human": 0,
  "humor": 0,
  "hunger": 0,
  "hunt": 0,
  "hurry": 0,
  "hurt": 0,
  "husband": 0,
  "I": 0, // tslint:disable-line
  "ice": 0,
  "idea": 0,
  "identify": 0,
  "if": 0,
  "illegal": 0,
  "imagine": 0,
  "immediate": 0,
  "immigrant": 0,
  "import": 0,
  "important": 0,
  "improve": 0,
  "in": 0,
  "incident": 0,
  "incite": 0,
  "include": 0,
  "increase": 0,
  "independent": 0,
  "individual": 0,
  "industry": 0,
  "infect": 0,
  "inflation": 0,
  "influence": 0,
  "inform": 0,
  "information": 0,
  "inject": 0,
  "injure": 0,
  "innocent": 0,
  "insane": 0,
  "insect": 0,
  "inspect": 0,
  "instead": 0,
  "instrument": 0,
  "insult": 0,
  "intelligence": 0,
  "intelligent": 0,
  "intense": 0,
  "interest": 0,
  "interfere": 0,
  "international": 0,
  "intervene": 0,
  "invade": 0,
  "invent": 0,
  "invest": 0,
  "investigate": 0,
  "invite": 0,
  "involve": 0,
  "iron": 0,
  "island": 0,
  "issue": 0,
  "it": 0,
  "jail": 0,
  "jewel": 0,
  "job": 0,
  "join": 0,
  "joint": 0,
  "joke": 0,
  "judge": 0,
  "jump": 0,
  "jury": 0,
  "just": 0,
  "keep": 0,
  "kick": 0,
  "kidnap": 0,
  "kill": 0,
  "kind": 0,
  "kiss": 0,
  "knife": 0,
  "know": 0,
  "knowledge": 0,
  "labor": 0,
  "laboratory": 0,
  "lack": 0,
  "lake": 0,
  "land": 0,
  "language": 0,
  "large": 0,
  "last": 0,
  "late": 0,
  "laugh": 0,
  "launch": 0,
  "law": 0,
  "lead": 0,
  "leak": 0,
  "learn": 0,
  "leave": 0,
  "left": 0,
  "legal": 0,
  "legislature": 0,
  "lend": 0,
  "less": 0,
  "let": 0,
  "letter": 0,
  "level": 0,
  "liberal": 0,
  "lie": 0,
  "life": 0,
  "lift": 0,
  "light": 0,
  "lightning": 0,
  "like": 0,
  "limit": 0,
  "line": 0,
  "link": 0,
  "liquid": 0,
  "list": 0,
  "listen": 0,
  "literature": 0,
  "little": 0,
  "live": 0,
  "load": 0,
  "loan": 0,
  "local": 0,
  "lonely": 0,
  "long": 0,
  "look": 0,
  "lose": 0,
  "loud": 0,
  "love": 0,
  "low": 0,
  "loyal": 0,
  "luck": 0,
  "machine": 0,
  "magazine": 0,
  "mail": 0,
  "main": 0,
  "major": 0,
  "majority": 0,
  "make": 0,
  "male": 0,
  "man": 0,
  "manufacture": 0,
  "many": 0,
  "map": 0,
  "march": 0,
  "mark": 0,
  "market": 0,
  "marry": 0,
  "mass": 0,
  "mate": 0,
  "material": 0,
  "mathematics": 0,
  "matter": 0,
  "may": 0,
  "mayor": 0,
  "meal": 0,
  "mean": 0,
  "measure": 0,
  "meat": 0,
  "media": 0,
  "medicine": 0,
  "meet": 0,
  "melt": 0,
  "member": 0,
  "memorial": 0,
  "memory": 0,
  "mental": 0,
  "mercy": 0,
  "message": 0,
  "metal": 0,
  "method": 0,
  "microscope": 0,
  "middle": 0,
  "militant": 0,
  "military": 0,
  "milk": 0,
  "mind": 0,
  "mine": 0,
  "mineral": 0,
  "minister": 0,
  "minor": 0,
  "minority": 0,
  "minute": 0,
  "miss": 0,
  "missile": 0,
  "missing": 0,
  "mistake": 0,
  "mix": 0,
  "mob": 0,
  "model": 0,
  "moderate": 0,
  "modern": 0,
  "money": 0,
  "month": 0,
  "moon": 0,
  "moral": 0,
  "more": 0,
  "morning": 0,
  "most": 0,
  "mother": 0,
  "motion": 0,
  "mountain": 0,
  "mourn": 0,
  "move": 0,
  "movement": 0,
  "movie": 0,
  "much": 0,
  "murder": 0,
  "music": 0,
  "must": 0,
  "mystery": 0,
  "name": 0,
  "narrow": 0,
  "nation": 0,
  "native": 0,
  "natural": 0,
  "nature": 0,
  "navy": 0,
  "near": 0,
  "necessary": 0,
  "need": 0,
  "negotiate": 0,
  "neither": 0,
  "neutral": 0,
  "never": 0,
  "new": 0,
  "news": 0,
  "next": 0,
  "nice": 0,
  "night": 0,
  "no": 0,
  "noise": 0,
  "nominate": 0,
  "noon": 0,
  "normal": 0,
  "north": 0,
  "not": 0,
  "note": 0,
  "nothing": 0,
  "now": 0,
  "nowhere": 0,
  "nuclear": 0,
  "number": 0,
  "obey": 0,
  "object": 0,
  "observe": 0,
  "occupy": 0,
  "ocean": 0,
  "of": 0,
  "off": 0,
  "offensive": 0,
  "offer": 0,
  "office": 0,
  "officer": 0,
  "official": 0,
  "often": 0,
  "oil": 0,
  "old": 0,
  "on": 0,
  "once": 0,
  "only": 0,
  "open": 0,
  "operate": 0,
  "opinion": 0,
  "oppose": 0,
  "opposite": 0,
  "oppress": 0,
  "or": 0,
  "orbit": 0,
  "order": 0,
  "organize": 0,
  "other": 0,
  "our": 0,
  "oust": 0,
  "out": 0,
  "over": 0,
  "overthrow": 0,
  "owe": 0,
  "own": 0,
  "pain": 0,
  "paint": 0,
  "pan": 0,
  "paper": 0,
  "parachute": 0,
  "parade": 0,
  "pardon": 0,
  "parent": 0,
  "parliament": 0,
  "part": 0,
  "party": 0,
  "pass": 0,
  "passenger": 0,
  "passport": 0,
  "past": 0,
  "path": 0,
  "patient": 0,
  "pay": 0,
  "peace": 0,
  "people": 0,
  "percent": 0,
  "perfect": 0,
  "perform": 0,
  "period": 0,
  "permanent": 0,
  "permit": 0,
  "person": 0,
  "physical": 0,
  "physics": 0,
  "picture": 0,
  "piece": 0,
  "pig": 0,
  "pilot": 0,
  "pipe": 0,
  "place": 0,
  "plan": 0,
  "planet": 0,
  "plant": 0,
  "plastic": 0,
  "play": 0,
  "please": 0,
  "plenty": 0,
  "plot": 0,
  "poem": 0,
  "point": 0,
  "poison": 0,
  "police": 0,
  "policy": 0,
  "politics": 0,
  "pollute": 0,
  "poor": 0,
  "popular": 0,
  "population": 0,
  "port": 0,
  "position": 0,
  "possess": 0,
  "possible": 0,
  "postpone": 0,
  "pour": 0,
  "poverty": 0,
  "power": 0,
  "praise": 0,
  "pray": 0,
  "pregnant": 0,
  "present": 0,
  "president": 0,
  "press": 0,
  "pressure": 0,
  "prevent": 0,
  "price": 0,
  "prison": 0,
  "private": 0,
  "prize": 0,
  "probably": 0,
  "problem": 0,
  "process": 0,
  "produce": 0,
  "profession": 0,
  "professor": 0,
  "profit": 0,
  "program": 0,
  "progress": 0,
  "project": 0,
  "propaganda": 0,
  "property": 0,
  "propose": 0,
  "protect": 0,
  "protest": 0,
  "prove": 0,
  "provide": 0,
  "public": 0,
  "publication": 0,
  "publish": 0,
  "pull": 0,
  "pump": 0,
  "punish": 0,
  "purchase": 0,
  "pure": 0,
  "purpose": 0,
  "push": 0,
  "put": 0,
  "quality": 0,
  "question": 0,
  "quick": 0,
  "quiet": 0,
  "race": 0,
  "radar": 0,
  "radiation": 0,
  "radio": 0,
  "raid": 0,
  "railroad": 0,
  "rain": 0,
  "raise": 0,
  "rare": 0,
  "rate": 0,
  "reach": 0,
  "react": 0,
  "read": 0,
  "ready": 0,
  "real": 0,
  "realistic": 0,
  "reason": 0,
  "reasonable": 0,
  "rebel": 0,
  "receive": 0,
  "recent": 0,
  "recession": 0,
  "recognize": 0,
  "record": 0,
  "recover": 0,
  "red": 0,
  "reduce": 0,
  "reform": 0,
  "refugee": 0,
  "refuse": 0,
  "regret": 0,
  "reject": 0,
  "relations": 0,
  "release": 0,
  "religion": 0,
  "remain": 0,
  "remains": 0,
  "remember": 0,
  "remove": 0,
  "repair": 0,
  "repeat": 0,
  "report": 0,
  "represent": 0,
  "repress": 0,
  "request": 0,
  "require": 0,
  "rescue": 0,
  "research": 0,
  "resign": 0,
  "resist": 0,
  "resolution": 0,
  "resource": 0,
  "responsible": 0,
  "rest": 0,
  "restrain": 0,
  "restrict": 0,
  "result": 0,
  "retire": 0,
  "return": 0,
  "revolt": 0,
  "rice": 0,
  "rich": 0,
  "ride": 0,
  "right": 0,
  "riot": 0,
  "rise": 0,
  "risk": 0,
  "river": 0,
  "road": 0,
  "rob": 0,
  "rock": 0,
  "rocket": 0,
  "roll": 0,
  "room": 0,
  "root": 0,
  "rope": 0,
  "rough": 0,
  "round": 0,
  "rub": 0,
  "rubber": 0,
  "ruin": 0,
  "rule": 0,
  "run": 0,
  "sabotage": 0,
  "sacrifice": 0,
  "sad": 0,
  "safe": 0,
  "sail": 0,
  "sailor": 0,
  "salt": 0,
  "same": 0,
  "sand": 0,
  "satellite": 0,
  "satisfy": 0,
  "save": 0,
  "say": 0,
  "school": 0,
  "science": 0,
  "sea": 0,
  "search": 0,
  "season": 0,
  "seat": 0,
  "second": 0,
  "secret": 0,
  "security": 0,
  "see": 0,
  "seed": 0,
  "seek": 0,
  "seem": 0,
  "seize": 0,
  "self": 0,
  "sell": 0,
  "Senate": 0,
  "send": 0,
  "sense": 0,
  "sentence": 0,
  "separate": 0,
  "series": 0,
  "serious": 0,
  "serve": 0,
  "service": 0,
  "set": 0,
  "settle": 0,
  "several": 0,
  "severe": 0,
  "sex": 0,
  "shake": 0,
  "shape": 0,
  "share": 0,
  "sharp": 0,
  "she": 0,
  "sheep": 0,
  "shell": 0,
  "shelter": 0,
  "shine": 0,
  "ship": 0,
  "shock": 0,
  "shoe": 0,
  "shoot": 0,
  "short": 0,
  "should": 0,
  "shout": 0,
  "show": 0,
  "shrink": 0,
  "sick": 0,
  "sickness": 0,
  "side": 0,
  "sign": 0,
  "signal": 0,
  "silence": 0,
  "silver": 0,
  "similar": 0,
  "simple": 0,
  "since": 0,
  "sing": 0,
  "single": 0,
  "sink": 0,
  "sister": 0,
  "sit": 0,
  "situation": 0,
  "size": 0,
  "skeleton": 0,
  "skill": 0,
  "skin": 0,
  "sky": 0,
  "slave": 0,
  "sleep": 0,
  "slide": 0,
  "slow": 0,
  "small": 0,
  "smash": 0,
  "smell": 0,
  "smoke": 0,
  "smooth": 0,
  "snow": 0,
  "so": 0,
  "social": 0,
  "soft": 0,
  "soil": 0,
  "soldier": 0,
  "solid": 0,
  "solve": 0,
  "some": 0,
  "son": 0,
  "soon": 0,
  "sort": 0,
  "sound": 0,
  "south": 0,
  "space": 0,
  "speak": 0,
  "special": 0,
  "speech": 0,
  "speed": 0,
  "spend": 0,
  "spill": 0,
  "spirit": 0,
  "split": 0,
  "sport": 0,
  "spread": 0,
  "spring": 0,
  "spy": 0,
  "square": 0,
  "stab": 0,
  "stand": 0,
  "star": 0,
  "start": 0,
  "starve": 0,
  "state": 0,
  "station": 0,
  "statue": 0,
  "stay": 0,
  "steal": 0,
  "steam": 0,
  "steel": 0,
  "step": 0,
  "stick": 0,
  "still": 0,
  "stone": 0,
  "stop": 0,
  "store": 0,
  "storm": 0,
  "story": 0,
  "stove": 0,
  "straight": 0,
  "strange": 0,
  "street": 0,
  "stretch": 0,
  "strike": 0,
  "strong": 0,
  "structure": 0,
  "struggle": 0,
  "study": 0,
  "stupid": 0,
  "subject": 0,
  "submarine": 0,
  "substance": 0,
  "substitute": 0,
  "subversion": 0,
  "succeed": 0,
  "such": 0,
  "sudden": 0,
  "suffer": 0,
  "sugar": 0,
  "suggest": 0,
  "summer": 0,
  "sun": 0,
  "supervise": 0,
  "supply": 0,
  "support": 0,
  "suppose": 0,
  "suppress": 0,
  "sure": 0,
  "surface": 0,
  "surplus": 0,
  "surprise": 0,
  "surrender": 0,
  "surround": 0,
  "survive": 0,
  "suspect": 0,
  "suspend": 0,
  "swallow": 0,
  "sweet": 0,
  "swim": 0,
  "sympathy": 0,
  "system": 0,
  "take": 0,
  "talk": 0,
  "tall": 0,
  "tank": 0,
  "target": 0,
  "taste": 0,
  "tax": 0,
  "tea": 0,
  "teach": 0,
  "team": 0,
  "tear": 0,
  "tears": 0,
  "technical": 0,
  "technology": 0,
  "telephone": 0,
  "telescope": 0,
  "television": 0,
  "tell": 0,
  "temperature": 0,
  "temporary": 0,
  "tense": 0,
  "term": 0,
  "terrible": 0,
  "territory": 0,
  "terror": 0,
  "terrorist": 0,
  "test": 0,
  "than": 0,
  "thank": 0,
  "that": IS_DETERMINER,
  "the": IS_DETERMINER,
  "theater": 0,
  "them": 0,
  "then": 0,
  "theory": 0,
  "there": 0,
  "these": 0,
  "they": 0,
  "thick": 0,
  "thin": 0,
  "thing": 0,
  "think": 0,
  "third": 0,
  "this": IS_DETERMINER,
  "threaten": 0,
  "through": 0,
  "throw": 0,
  "tie": 0,
  "time": 0,
  "tired": 0,
  "to": 0,
  "today": 0,
  "together": 0,
  "tomorrow": 0,
  "tonight": 0,
  "too": 0,
  "tool": 0,
  "top": 0,
  "torture": 0,
  "total": 0,
  "touch": 0,
  "toward": 0,
  "town": 0,
  "trade": 0,
  "tradition": 0,
  "traffic": 0,
  "tragic": 0,
  "train": 0,
  "transport": 0,
  "transportation": 0,
  "trap": 0,
  "travel": 0,
  "treason": 0,
  "treasure": 0,
  "treat": 0,
  "treatment": 0,
  "treaty": 0,
  "tree": 0,
  "trial": 0,
  "tribe": 0,
  "trick": 0,
  "trip": 0,
  "troops": 0,
  "trouble": 0,
  "truce": 0,
  "truck": 0,
  "true": 0,
  "trust": 0,
  "try": 0,
  "tube": 0,
  "turn": 0,
  "under": 0,
  "understand": 0,
  "unite": 0,
  "universe": 0,
  "university": 0,
  "unless": 0,
  "until": 0,
  "up": 0,
  "urge": 0,
  "urgent": 0,
  "us": 0,
  "use": 0,
  "usual": 0,
  "valley": 0,
  "value": 0,
  "vegetable": 0,
  "vehicle": 0,
  "version": 0,
  "very": 0,
  "veto": 0,
  "vicious": 0,
  "victim": 0,
  "victory": 0,
  "village": 0,
  "violate": 0,
  "violence": 0,
  "visit": 0,
  "voice": 0,
  "volcano": 0,
  "vote": 0,
  "wages": 0,
  "wait": 0,
  "walk": 0,
  "wall": 0,
  "want": 0,
  "war": 0,
  "warm": 0,
  "warn": 0,
  "wash": 0,
  "waste": 0,
  "watch": 0,
  "water": 0,
  "wave": 0,
  "way": 0,
  "we": 0,
  "weak": 0,
  "wealth": 0,
  "weapon": 0,
  "wear": 0,
  "weather": 0,
  "week": 0,
  "weigh": 0,
  "welcome": 0,
  "well": 0,
  "west": 0,
  "wet": 0,
  "what": 0,
  "wheat": 0,
  "wheel": 0,
  "when": 0,
  "where": 0,
  "which": 0,
  "while": 0,
  "white": 0,
  "who": 0,
  "whole": 0,
  "why": 0,
  "wide": 0,
  "wife": 0,
  "wild": 0,
  "will": 0,
  "willing": 0,
  "win": 0,
  "wind": 0,
  "window": 0,
  "winter": 0,
  "wire": 0,
  "wise": 0,
  "wish": 0,
  "with": 0,
  "withdraw": 0,
  "without": 0,
  "woman": 0,
  "wonder": 0,
  "wonderful": 0,
  "wood": 0,
  "word": 0,
  "work": 0,
  "world": 0,
  "worry": 0,
  "worse": 0,
  "worth": 0,
  "wound": 0,
  "wreck": 0,
  "wreckage": 0,
  "write": 0,
  "wrong": 0,
  "year": 0,
  "yellow": 0,
  "yes": 0,
  "yesterday": IS_NOUN | IS_ADVERB,
  "yet": IS_CONJUNCTION,
  "you": 0,
  "young": 0,
  "zero": 0,
  "zoo": 0,
  "atom": 0,
  "bacteria": 0,
  "cell": 0,
  "chromosome": 0,
  "compound": 0,
  "dense": 0,
  "electron": 0,
  "element": 0,
  "enzyme": 0,
  "fetus": 0,
  "fission": 0,
  "fusion": 0,
  "gene": 0,
  "gravity": 0,
  "image": 0,
  "laser": 0,
  "magnet": 0,
  "molecule": 0,
  "nerve": 0,
  "nucleus": 0,
  "nutrient": 0,
  "organ": 0,
  "organism": 0,
  "particle": 0,
  "protein": 0,
  "robot": 0,
  "tissue": 0,
  "virus": 0,
  "x-rays": 0,
  "heart": 0,
  "intestines": 0,
  "kidney": 0,
  "liver": 0,
  "lung": 0,
  "prostate": 0,
  "stomach": 0,
  "uterus": 0,
};

export const allWords = () =>
  Object.entries(VOA_MAP)
    .map((kv) => kv[0]);

export const nouns = () =>
  Object.entries(VOA_MAP)
    .filter((kv) => kv[1] & IS_NOUN)
    .map((kv) => kv[0]);

export const verbs = () =>
  Object.entries(VOA_MAP)
    .filter((kv) => kv[1] & IS_VERB)
    .map((kv) => kv[0]);

export const adjectives = () =>
  Object.entries(VOA_MAP)
    .filter((kv) => kv[1] & IS_ADJECTIVE)
    .map((kv) => kv[0]);

export const adverbs = () =>
  Object.entries(VOA_MAP)
    .filter((kv) => kv[1] & IS_ADVERB)
    .map((kv) => kv[0]);

export const prepositions = () =>
  Object.entries(VOA_MAP)
    .filter((kv) => kv[1] & IS_PREPOSITION)
    .map((kv) => kv[0]);

export const conjunctions = () =>
  Object.entries(VOA_MAP)
    .filter((kv) => kv[1] & IS_CONJUNCTION)
    .map((kv) => kv[0]);

export const determiners = () =>
  Object.entries(VOA_MAP)
    .filter((kv) => kv[1] & IS_DETERMINER)
    .map((kv) => kv[0]);
