// https://en.wikipedia.org/wiki/Part_of_speech
const IS_NOUN = 1;
const IS_VERB = 2;
const IS_ADJECTIVE = 4;
const IS_ADVERB = 8;
const IS_PREPOSITION = 16;
const IS_CONJUNCTION = 32;
const IS_DETERMINER = 64;

/**
 * These words are Voice Of America Special English.
 * See the `voa/` subdirectory for a script that generates the word bank.
 *
 * Rules of phrase.shop:
 * 1. nouns must be singular
 * 2. verbs must be plural ("people JOIN" rather than "person JOINS")
 */
const VOA_MAP = {
  "a": IS_DETERMINER,
  "able": IS_VERB | IS_ADJECTIVE,
  "about": IS_ADVERB | IS_ADJECTIVE | IS_PREPOSITION,
  "above": IS_ADVERB | IS_PREPOSITION,
  "accept": IS_VERB,
  "accident": IS_NOUN,
  "accuse": IS_VERB,
  "across": IS_ADVERB | IS_PREPOSITION,
  "act": IS_NOUN | IS_VERB,
  "activist": IS_NOUN,
  "actor": IS_NOUN,
  "add": IS_VERB,
  "administration": IS_NOUN,
  "admit": IS_VERB | IS_NOUN,
  "adult": IS_ADJECTIVE | IS_NOUN,
  "advise": IS_VERB,
  "affect": IS_VERB,
  "afraid": IS_ADJECTIVE,
  "after": IS_ADVERB | IS_CONJUNCTION | IS_PREPOSITION,
  "again": IS_ADVERB,
  "against": IS_PREPOSITION,
  "age": IS_VERB | IS_NOUN,
  "agency": IS_NOUN,
  "aggression": IS_NOUN,
  "ago": IS_ADJECTIVE | IS_ADVERB,
  "agree": IS_VERB,
  "agriculture": IS_NOUN,
  "aid": IS_VERB | IS_NOUN,
  "aim": IS_VERB | IS_NOUN,
  "air": IS_VERB | IS_NOUN,
  "airplane": IS_NOUN,
  "airport": IS_NOUN,
  "album": IS_NOUN,
  "alcohol": IS_NOUN,
  "alive": IS_ADJECTIVE,
  "all": IS_DETERMINER | IS_ADVERB,
  "ally": IS_NOUN | IS_VERB,
  "almost": IS_ADVERB,
  "alone": IS_ADJECTIVE | IS_ADVERB,
  "along": IS_PREPOSITION | IS_ADVERB,
  "already": IS_ADVERB,
  "also": IS_ADVERB,
  "although": IS_CONJUNCTION,
  "always": IS_ADVERB,
  "ambassador": IS_NOUN,
  "amend": IS_VERB,
  "ammunition": IS_NOUN,
  "among": IS_PREPOSITION,
  "amount": IS_NOUN,
  "anarchy": IS_NOUN,
  "ancestor": IS_NOUN,
  "ancient": IS_ADJECTIVE,
  "and": IS_CONJUNCTION,
  "anger": IS_NOUN | IS_VERB,
  "animal": IS_NOUN | IS_VERB,
  "anniversary": IS_NOUN,
  "announce": IS_VERB,
  "another": IS_DETERMINER,
  "answer": IS_NOUN | IS_VERB,
  "any": IS_ADVERB | IS_DETERMINER,
  "apologize": IS_VERB,
  "appeal": IS_VERB | IS_NOUN,
  "appear": IS_VERB,
  "appoint": IS_VERB,
  "approve": IS_VERB,
  "archeology": IS_NOUN,
  "area": IS_NOUN,
  "argue": IS_VERB,
  "arms": IS_NOUN,
  "army": IS_NOUN,
  "around": IS_PREPOSITION,
  "arrest": IS_NOUN | IS_VERB,
  "arrive": IS_VERB,
  "art": IS_NOUN,
  "artillery": IS_NOUN,
  "as": IS_ADVERB | IS_CONJUNCTION | IS_PREPOSITION,
  "ash": IS_NOUN,
  "ask": IS_VERB | IS_NOUN,
  "assist": IS_VERB | IS_NOUN,
  "astronaut": IS_NOUN,
  "astronomy": IS_NOUN,
  "asylum": IS_NOUN,
  "at": IS_PREPOSITION,
  "atmosphere": IS_NOUN,
  "attach": IS_VERB,
  "attack": IS_NOUN | IS_VERB,
  "attempt": IS_NOUN | IS_VERB,
  "attend": IS_VERB,
  "automobile": IS_NOUN,
  "autumn": IS_NOUN,
  "average": IS_NOUN | IS_VERB,
  "avoid": IS_VERB,
  "awake": IS_ADJECTIVE,
  "award": IS_VERB | IS_NOUN,
  "away": IS_ADVERB,
  "baby": IS_NOUN | IS_ADJECTIVE,
  "back": IS_ADJECTIVE | IS_ADVERB,
  "bad": IS_ADJECTIVE | IS_ADVERB,
  "balance": IS_NOUN | IS_VERB,
  "ball": IS_NOUN,
  "balloon": IS_NOUN,
  "ballot": IS_NOUN,
  "ban": IS_NOUN | IS_VERB,
  "bank": IS_NOUN | IS_VERB,
  "bar": IS_NOUN | IS_VERB,
  "barrier": IS_NOUN,
  "base": IS_NOUN | IS_VERB,
  "battle": IS_NOUN | IS_VERB,
  "be": IS_VERB,
  "beat": IS_NOUN | IS_VERB,
  "beauty": IS_NOUN,
  "because": IS_ADVERB | IS_CONJUNCTION,
  "become": IS_VERB,
  "bed": IS_NOUN,
  "before": IS_PREPOSITION | IS_ADVERB | IS_CONJUNCTION,
  "begin": IS_VERB,
  "behind": IS_PREPOSITION | IS_ADVERB | IS_NOUN,
  "believe": IS_VERB,
  "bell": IS_NOUN,
  "belong": IS_VERB,
  "below": IS_PREPOSITION | IS_ADVERB,
  "best": IS_ADJECTIVE | IS_ADVERB | IS_NOUN | IS_VERB,
  "betray": IS_VERB,
  "better": IS_ADJECTIVE | IS_ADVERB | IS_NOUN,
  "between": IS_PREPOSITION,
  "big": IS_ADJECTIVE | IS_ADVERB,
  "bill": IS_VERB | IS_NOUN,
  "biology": IS_NOUN,
  "bird": IS_NOUN,
  "bite": IS_NOUN | IS_VERB,
  "black": IS_ADJECTIVE | IS_NOUN,
  "blame": IS_NOUN | IS_VERB,
  "blanket": IS_NOUN,
  "bleed": IS_VERB,
  "blind": IS_NOUN | IS_VERB,
  "block": IS_NOUN | IS_VERB,
  "blood": IS_NOUN,
  "blow": IS_NOUN | IS_VERB,
  "blue": IS_ADJECTIVE | IS_NOUN,
  "boat": IS_NOUN,
  "body": IS_NOUN,
  "boil": IS_NOUN | IS_VERB,
  "bomb": IS_NOUN | IS_VERB,
  "bone": IS_NOUN,
  "book": IS_NOUN | IS_VERB,
  "border": IS_NOUN | IS_VERB,
  "born": IS_VERB | IS_ADJECTIVE,
  "borrow": IS_VERB,
  "both": IS_DETERMINER | IS_CONJUNCTION,
  "bottle": IS_NOUN | IS_VERB,
  "bottom": IS_NOUN | IS_ADJECTIVE,
  "box": IS_NOUN | IS_VERB,
  "boy": IS_NOUN,
  "boycott": IS_NOUN | IS_VERB,
  "brain": IS_NOUN,
  "brave": IS_ADJECTIVE | IS_VERB,
  "bread": IS_NOUN,
  "break": IS_NOUN | IS_VERB,
  "breathe": IS_VERB,
  "bridge": IS_NOUN | IS_VERB,
  "brief": IS_NOUN | IS_ADJECTIVE | IS_VERB,
  "bright": IS_ADJECTIVE,
  "bring": IS_VERB,
  "broadcast": IS_VERB | IS_NOUN,
  "brother": IS_NOUN,
  "brown": IS_NOUN | IS_ADJECTIVE | IS_VERB,
  "budget": IS_NOUN,
  "build": IS_VERB | IS_NOUN,
  "building": IS_NOUN,
  "bullet": IS_NOUN,
  "burn": IS_NOUN | IS_VERB,
  "burst": IS_NOUN | IS_VERB,
  "bury": IS_VERB,
  "bus": IS_NOUN | IS_VERB,
  "business": IS_NOUN,
  "busy": IS_ADJECTIVE | IS_VERB,
  "but": IS_PREPOSITION | IS_CONJUNCTION,
  "buy": IS_VERB,
  "by": IS_PREPOSITION | IS_ADVERB | IS_ADJECTIVE,
  "cabinet": IS_NOUN,
  "call": IS_NOUN | IS_VERB,
  "calm": IS_ADJECTIVE | IS_NOUN | IS_VERB,
  "camera": IS_NOUN,
  "camp": IS_NOUN | IS_VERB,
  "campaign": IS_VERB | IS_NOUN,
  "can": IS_NOUN | IS_VERB,
  "cancel": IS_VERB,
  "cancer": IS_NOUN,
  "candidate": IS_NOUN,
  "capital": IS_NOUN,
  "capitalism": IS_NOUN,
  "capture": IS_NOUN | IS_VERB,
  "car": IS_NOUN,
  "care": IS_NOUN | IS_VERB,
  "careful": IS_ADJECTIVE,
  "carry": IS_VERB,
  "case": IS_VERB | IS_NOUN,
  "cat": IS_NOUN,
  "catch": IS_VERB | IS_NOUN,
  "cause": IS_NOUN | IS_VERB,
  "ceasefire": IS_NOUN,
  "celebrate": IS_VERB,
  "center": IS_NOUN | IS_ADJECTIVE | IS_VERB,
  "century": IS_NOUN,
  "ceremony": IS_NOUN,
  "chairman": IS_NOUN,
  "champion": IS_NOUN,
  "chance": IS_NOUN | IS_VERB,
  "change": IS_NOUN | IS_VERB,
  "charge": IS_NOUN | IS_VERB,
  "chase": IS_NOUN | IS_VERB,
  "cheat": IS_NOUN | IS_VERB,
  "cheer": IS_NOUN | IS_VERB,
  "chemical": IS_NOUN | IS_ADJECTIVE,
  "chemistry": IS_NOUN,
  "chief": IS_NOUN | IS_ADJECTIVE,
  "child": IS_NOUN,
  "children": IS_NOUN,
  "choose": IS_VERB,
  "circle": IS_NOUN | IS_VERB,
  "citizen": IS_NOUN,
  "city": IS_NOUN,
  "civilian": IS_NOUN,
  "claim": IS_NOUN | IS_VERB,
  "clash": IS_NOUN | IS_VERB,
  "clean": IS_ADJECTIVE | IS_VERB,
  "clear": IS_ADJECTIVE | IS_ADVERB | IS_VERB,
  "clergy": IS_NOUN,
  "climate": IS_NOUN,
  "climb": IS_NOUN | IS_VERB,
  "clock": IS_NOUN,
  "close": IS_VERB | IS_NOUN | IS_ADJECTIVE,
  "cloth": IS_NOUN,
  "clothes": IS_NOUN,
  "cloud": IS_NOUN,
  "coal": IS_NOUN,
  "coalition": IS_NOUN,
  "coast": IS_NOUN | IS_VERB,
  "coffee": IS_NOUN,
  "cold": IS_ADJECTIVE | IS_NOUN,
  "collect": IS_VERB,
  "college": IS_NOUN,
  "colony": IS_NOUN,
  "color": IS_NOUN | IS_VERB,
  "combine": IS_VERB,
  "come": IS_VERB,
  "command": IS_VERB | IS_NOUN,
  "comment": IS_VERB | IS_NOUN,
  "committee": IS_NOUN,
  "common": IS_ADJECTIVE,
  "communicate": IS_VERB,
  "community": IS_NOUN,
  "company": IS_NOUN,
  "compare": IS_VERB,
  "compete": IS_VERB,
  "complete": IS_VERB | IS_ADJECTIVE,
  "complex": IS_ADJECTIVE | IS_NOUN,
  "compromise": IS_VERB | IS_NOUN,
  "computer": IS_NOUN,
  "concern": IS_NOUN | IS_VERB,
  "condemn": IS_VERB,
  "condition": IS_NOUN | IS_VERB,
  "conference": IS_NOUN,
  "confirm": IS_VERB,
  "conflict": IS_NOUN,
  "congratulate": IS_VERB,
  "congress": IS_NOUN,
  "connect": IS_VERB,
  "conservative": IS_ADJECTIVE | IS_NOUN,
  "consider": IS_VERB,
  "constitution": IS_NOUN,
  "contain": IS_VERB,
  "container": IS_NOUN,
  "continent": IS_NOUN,
  "continue": IS_VERB,
  "control": IS_NOUN | IS_VERB,
  "convention": IS_NOUN,
  "cook": IS_NOUN | IS_VERB,
  "cool": IS_ADJECTIVE | IS_NOUN | IS_VERB,
  "cooperate": IS_VERB,
  "copy": IS_VERB | IS_NOUN,
  "corn": IS_NOUN,
  "correct": IS_ADJECTIVE | IS_VERB,
  "cost": IS_VERB | IS_NOUN,
  "cotton": IS_ADJECTIVE | IS_NOUN,
  "count": IS_VERB | IS_NOUN,
  "country": IS_NOUN | IS_ADJECTIVE,
  "court": IS_NOUN | IS_VERB,
  "cover": IS_NOUN | IS_VERB,
  "cow": IS_NOUN,
  "crash": IS_NOUN | IS_VERB,
  "create": IS_VERB,
  "creature": IS_NOUN,
  "credit": IS_NOUN | IS_VERB,
  "crew": IS_NOUN | IS_VERB,
  "crime": IS_NOUN,
  "criminal": IS_NOUN,
  "crisis": IS_NOUN,
  "criticize": IS_VERB,
  "crops": IS_NOUN,
  "cross": IS_NOUN | IS_VERB,
  "crowd": IS_NOUN | IS_VERB,
  "crush": IS_NOUN | IS_VERB,
  "cry": IS_NOUN | IS_VERB,
  "culture": IS_NOUN | IS_VERB,
  "cure": IS_NOUN | IS_VERB,
  "curfew": IS_NOUN,
  "current": IS_NOUN | IS_ADJECTIVE,
  "custom": IS_NOUN | IS_ADJECTIVE,
  "customs": IS_NOUN,
  "cut": IS_NOUN | IS_VERB | IS_ADJECTIVE,
  "dam": IS_NOUN | IS_VERB,
  "damage": IS_NOUN | IS_VERB,
  "dance": IS_NOUN | IS_VERB,
  "danger": IS_NOUN,
  "dark": IS_ADJECTIVE,
  "date": IS_NOUN | IS_VERB,
  "daughter": IS_NOUN,
  "day": IS_NOUN,
  "dead": IS_ADJECTIVE | IS_ADVERB | IS_NOUN,
  "deaf": IS_ADJECTIVE,
  "deal": IS_NOUN | IS_VERB,
  "debate": IS_NOUN | IS_VERB,
  "debt": IS_NOUN,
  "decide": IS_VERB,
  "declare": IS_VERB,
  "decrease": IS_VERB,
  "deep": IS_ADJECTIVE | IS_ADVERB,
  "defeat": IS_VERB | IS_NOUN,
  "defend": IS_VERB,
  "deficit": IS_NOUN,
  "define": IS_VERB,
  "degree": IS_NOUN,
  "delay": IS_NOUN | IS_VERB,
  "delegate": IS_VERB,
  "demand": IS_NOUN | IS_VERB,
  "democracy": IS_NOUN,
  "demonstrate": IS_VERB,
  "denounce": IS_VERB,
  "deny": IS_VERB,
  "depend": IS_VERB,
  "deplore": IS_VERB,
  "deploy": IS_VERB,
  "depression": IS_NOUN,
  "describe": IS_VERB,
  "desert": IS_NOUN,
  "design": IS_NOUN | IS_VERB,
  "desire": IS_NOUN | IS_VERB,
  "destroy": IS_VERB,
  "detail": IS_NOUN | IS_VERB,
  "develop": IS_VERB,
  "device": IS_NOUN,
  "dictator": IS_NOUN,
  "die": IS_VERB | IS_NOUN,
  "diet": IS_VERB | IS_NOUN,
  "different": IS_ADJECTIVE | IS_ADVERB,
  "difficult": IS_ADJECTIVE,
  "dig": IS_VERB | IS_NOUN,
  "dinner": IS_NOUN,
  "diplomat": IS_NOUN,
  "direct": IS_VERB | IS_ADJECTIVE | IS_ADVERB,
  "direction": IS_NOUN,
  "dirt": IS_NOUN | IS_ADJECTIVE,
  "disappear": IS_VERB,
  "disarm": IS_VERB,
  "discover": IS_VERB,
  "discuss": IS_VERB,
  "disease": IS_NOUN,
  "dismiss": IS_VERB,
  "dispute": IS_NOUN | IS_VERB,
  "dissident": IS_NOUN,
  "distance": IS_NOUN | IS_VERB,
  "dive": IS_NOUN | IS_VERB,
  "divide": IS_NOUN | IS_VERB,
  "do": IS_VERB,
  "doctor": IS_NOUN | IS_VERB,
  "document": IS_NOUN | IS_VERB,
  "dog": IS_NOUN,
  "dollar": IS_NOUN,
  "door": IS_NOUN,
  "down": IS_PREPOSITION | IS_ADJECTIVE | IS_ADVERB | IS_VERB,
  "dream": IS_NOUN | IS_VERB,
  "drink": IS_NOUN | IS_VERB,
  "drive": IS_NOUN | IS_VERB,
  "drop": IS_NOUN | IS_VERB,
  "drown": IS_VERB,
  "drug": IS_NOUN | IS_VERB,
  "dry": IS_ADJECTIVE | IS_VERB,
  "during": IS_PREPOSITION,
  "dust": IS_NOUN | IS_VERB,
  "duty": IS_NOUN,
  "each": IS_DETERMINER | IS_ADVERB,
  "early": IS_ADJECTIVE | IS_ADVERB,
  "earn": IS_VERB,
  "earth": IS_NOUN,
  "earthquake": IS_NOUN,
  "ease": IS_NOUN | IS_VERB,
  "east": IS_NOUN | IS_ADJECTIVE,
  "easy": IS_ADJECTIVE | IS_ADVERB,
  "eat": IS_VERB,
  "ecology": IS_NOUN,
  "economy": IS_NOUN,
  "edge": IS_NOUN | IS_VERB,
  "education": IS_NOUN,
  "effect": IS_NOUN | IS_VERB,
  "effort": IS_NOUN,
  "egg": IS_NOUN,
  "either": IS_DETERMINER | IS_ADVERB | IS_CONJUNCTION,
  "elect": IS_NOUN | IS_VERB | IS_ADJECTIVE,
  "electricity": IS_NOUN,
  "embassy": IS_NOUN,
  "emergency": IS_NOUN,
  "emotion": IS_NOUN,
  "employ": IS_NOUN | IS_VERB,
  "empty": IS_ADJECTIVE | IS_VERB,
  "end": IS_NOUN | IS_VERB,
  "enemy": IS_NOUN,
  "energy": IS_NOUN,
  "enforce": IS_VERB,
  "engine": IS_NOUN,
  "engineer": IS_NOUN | IS_VERB,
  "enjoy": IS_VERB,
  "enough": IS_DETERMINER | IS_ADVERB,
  "enter": IS_VERB,
  "environment": IS_NOUN,
  "equal": IS_ADJECTIVE | IS_VERB,
  "equipment": IS_NOUN,
  "escape": IS_NOUN | IS_VERB,
  "especially": IS_ADVERB,
  "establish": IS_VERB,
  "estimate": IS_NOUN | IS_VERB,
  "ethnic": IS_ADJECTIVE,
  "evaporate": IS_VERB,
  "even": IS_ADJECTIVE | IS_VERB | IS_ADVERB,
  "event": IS_NOUN,
  "ever": IS_ADVERB,
  "every": IS_DETERMINER,
  "evidence": IS_NOUN,
  "evil": IS_ADJECTIVE | IS_NOUN,
  "exact": IS_ADJECTIVE | IS_VERB,
  "examine": IS_VERB,
  "example": IS_NOUN,
  "excellent": IS_ADJECTIVE,
  "except": IS_VERB | IS_PREPOSITION | IS_CONJUNCTION,
  "exchange": IS_NOUN | IS_VERB,
  "excuse": IS_NOUN | IS_VERB,
  "execute": IS_VERB,
  "exercise": IS_NOUN | IS_VERB,
  "exile": IS_NOUN | IS_VERB,
  "exist": IS_VERB,
  "expand": IS_VERB,
  "expect": IS_VERB,
  "expel": IS_VERB,
  "experience": IS_VERB | IS_NOUN,
  "experiment": IS_VERB | IS_NOUN,
  "expert": IS_NOUN | IS_ADJECTIVE,
  "explain": IS_VERB,
  "explode": IS_VERB,
  "explore": IS_VERB,
  "export": IS_VERB | IS_NOUN,
  "express": IS_ADJECTIVE | IS_NOUN | IS_VERB,
  "extend": IS_VERB,
  "extra": IS_ADJECTIVE | IS_ADVERB | IS_NOUN,
  "extreme": IS_ADJECTIVE | IS_NOUN,
  "extremist": IS_NOUN,
  "face": IS_NOUN | IS_VERB,
  "fact": IS_NOUN,
  "factory": IS_NOUN,
  "fail": IS_VERB,
  "fair": IS_ADJECTIVE | IS_NOUN | IS_VERB | IS_ADVERB,
  "fall": IS_VERB | IS_NOUN,
  "false": IS_ADJECTIVE | IS_ADVERB | IS_NOUN,
  "family": IS_ADJECTIVE | IS_NOUN,
  "famous": IS_ADJECTIVE,
  "far": IS_ADJECTIVE | IS_ADVERB,
  "farm": IS_NOUN | IS_VERB,
  "fast": IS_ADJECTIVE | IS_ADVERB | IS_NOUN,
  "fat": IS_ADJECTIVE | IS_NOUN,
  "father": IS_NOUN | IS_VERB,
  "fear": IS_NOUN | IS_VERB,
  "federal": IS_ADJECTIVE,
  "feed": IS_VERB | IS_NOUN,
  "feel": IS_VERB | IS_NOUN,
  "female": IS_ADJECTIVE | IS_NOUN,
  "fence": IS_NOUN,
  "fertile": IS_ADJECTIVE,
  "few": IS_DETERMINER,
  "field": IS_NOUN | IS_VERB,
  "fierce": IS_ADJECTIVE,
  "fight": IS_VERB | IS_NOUN,
  "fill": IS_VERB | IS_NOUN,
  "film": IS_VERB | IS_NOUN,
  "final": IS_NOUN | IS_ADJECTIVE,
  "financial": IS_ADJECTIVE,
  "find": IS_VERB | IS_NOUN,
  "fine": IS_ADJECTIVE | IS_ADVERB | IS_NOUN | IS_VERB,
  "finish": IS_NOUN | IS_VERB,
  "fire": IS_NOUN | IS_VERB,
  "fireworks": IS_NOUN,
  "firm": IS_NOUN | IS_ADJECTIVE,
  "first": IS_ADJECTIVE | IS_ADVERB | IS_NOUN,
  "fish": IS_NOUN | IS_VERB,
  "fit": IS_ADJECTIVE | IS_VERB | IS_NOUN,
  "fix": IS_VERB | IS_NOUN,
  "flag": IS_VERB | IS_NOUN,
  "flat": IS_ADJECTIVE | IS_ADVERB | IS_NOUN,
  "flee": IS_VERB,
  "float": IS_VERB | IS_NOUN,
  "flood": IS_VERB | IS_NOUN,
  "floor": IS_NOUN,
  "flow": IS_NOUN | IS_VERB,
  "flower": IS_NOUN | IS_VERB,
  "fluid": IS_NOUN | IS_ADJECTIVE,
  "fly": IS_NOUN | IS_VERB,
  "fog": IS_NOUN | IS_VERB,
  "follow": IS_VERB,
  "food": IS_NOUN,
  "fool": IS_NOUN | IS_VERB,
  "foot": IS_NOUN | IS_VERB,
  "for": IS_CONJUNCTION,
  "force": IS_NOUN | IS_VERB,
  "foreign": IS_ADJECTIVE,
  "forest": IS_NOUN,
  "forget": IS_VERB,
  "forgive": IS_VERB,
  "form": IS_NOUN | IS_VERB,
  "former": IS_ADJECTIVE,
  "forward": IS_ADJECTIVE | IS_ADVERB | IS_VERB,
  "free": IS_ADJECTIVE | IS_ADVERB | IS_VERB,
  "freedom": IS_NOUN,
  "freeze": IS_VERB | IS_NOUN,
  "fresh": IS_ADJECTIVE | IS_ADVERB,
  "friend": IS_NOUN,
  "frighten": IS_VERB,
  "from": IS_PREPOSITION,
  "front": IS_NOUN | IS_ADJECTIVE,
  "fruit": IS_NOUN | IS_VERB,
  "fuel": IS_NOUN | IS_VERB,
  "full": IS_ADJECTIVE,
  "fun": IS_NOUN | IS_ADJECTIVE,
  "funeral": IS_NOUN,
  "future": IS_NOUN | IS_ADJECTIVE,
  "gain": IS_NOUN | IS_VERB,
  "game": IS_NOUN | IS_VERB,
  "gas": IS_NOUN,
  "gather": IS_VERB,
  "general": IS_ADJECTIVE | IS_NOUN,
  "gentle": IS_ADJECTIVE,
  "get": IS_VERB,
  "gift": IS_NOUN | IS_VERB,
  "girl": IS_NOUN,
  "give": IS_VERB,
  "glass": IS_ADJECTIVE | IS_NOUN,
  "go": IS_VERB | IS_NOUN,
  "goal": IS_ADJECTIVE | IS_NOUN,
  "god": IS_NOUN,
  "gold": IS_ADJECTIVE | IS_NOUN,
  "good": IS_ADJECTIVE | IS_NOUN,
  "goods": IS_NOUN,
  "govern": IS_VERB,
  "government": IS_NOUN,
  "grain": IS_NOUN,
  "granddaughter": IS_NOUN,
  "grandfather": IS_NOUN,
  "grandmother": IS_NOUN,
  "grandson": IS_NOUN,
  "grass": IS_NOUN,
  "gray": IS_ADJECTIVE | IS_VERB | IS_NOUN,
  "great": IS_ADJECTIVE | IS_NOUN,
  "green": IS_ADJECTIVE | IS_NOUN,
  "grind": IS_NOUN | IS_VERB,
  "ground": IS_ADJECTIVE | IS_NOUN | IS_VERB,
  "group": IS_ADJECTIVE | IS_NOUN | IS_VERB,
  "grow": IS_VERB,
  "guarantee": IS_NOUN | IS_VERB,
  "guard": IS_NOUN | IS_VERB,
  "guerrilla": IS_ADJECTIVE | IS_NOUN,
  "guide": IS_NOUN | IS_VERB,
  "guilty": IS_ADJECTIVE,
  "gun": IS_NOUN,
  "hair": IS_NOUN,
  "half": IS_ADJECTIVE | IS_ADVERB | IS_NOUN,
  "halt": IS_NOUN | IS_VERB,
  "hang": IS_NOUN | IS_VERB,
  "happen": IS_VERB,
  "happy": IS_ADJECTIVE,
  "hard": IS_ADJECTIVE | IS_ADVERB,
  "harm": IS_NOUN | IS_VERB,
  "harvest": IS_NOUN | IS_VERB,
  "hat": IS_NOUN,
  "hate": IS_NOUN | IS_VERB,
  "have": IS_VERB,
  "he": 0, // pronoun, which we do not classify
  "head": IS_NOUN | IS_ADJECTIVE | IS_VERB,
  "headquarters": IS_NOUN,
  "heal": IS_VERB,
  "health": IS_NOUN,
  "hear": IS_VERB,
  "heat": IS_NOUN | IS_VERB,
  "heavy": IS_ADJECTIVE,
  "helicopter": IS_NOUN,
  "help": IS_NOUN | IS_VERB,
  "here": IS_ADVERB | IS_NOUN | IS_ADJECTIVE,
  "hero": IS_NOUN,
  "hide": IS_NOUN | IS_VERB,
  "high": IS_ADJECTIVE | IS_ADVERB | IS_NOUN,
  "hijack": IS_VERB | IS_NOUN,
  "hill": IS_NOUN,
  "history": IS_NOUN,
  "hit": IS_VERB | IS_NOUN | IS_ADJECTIVE,
  "hold": IS_VERB | IS_NOUN,
  "hole": IS_NOUN | IS_VERB,
  "holiday": IS_NOUN,
  "holy": IS_ADJECTIVE,
  "home": IS_NOUN | IS_ADJECTIVE | IS_ADVERB,
  "honest": IS_ADJECTIVE,
  "honor": IS_NOUN | IS_VERB,
  "hope": IS_NOUN | IS_VERB,
  "horrible": IS_ADJECTIVE,
  "horse": IS_NOUN,
  "hospital": IS_NOUN,
  "hostage": IS_NOUN,
  "hostile": IS_ADJECTIVE,
  "hot": IS_ADJECTIVE,
  "hotel": IS_NOUN,
  "hour": IS_NOUN,
  "house": IS_ADJECTIVE | IS_NOUN,
  "how": IS_ADVERB | IS_CONJUNCTION,
  "however": IS_ADVERB | IS_CONJUNCTION,
  "huge": IS_ADJECTIVE,
  "human": IS_ADJECTIVE | IS_NOUN,
  "humor": IS_NOUN | IS_VERB,
  "hunger": IS_NOUN | IS_VERB,
  "hunt": IS_NOUN | IS_VERB,
  "hurry": IS_NOUN | IS_VERB,
  "hurt": IS_VERB | IS_ADJECTIVE | IS_NOUN,
  "husband": IS_NOUN | IS_VERB,
  "I": 0, // tslint:disable-line
  "ice": IS_NOUN | IS_VERB,
  "idea": IS_NOUN,
  "identify": IS_VERB,
  "if": IS_CONJUNCTION,
  "illegal": IS_ADJECTIVE,
  "imagine": IS_VERB,
  "immediate": IS_ADJECTIVE,
  "immigrant": IS_NOUN | IS_ADJECTIVE,
  "import": IS_NOUN | IS_VERB,
  "important": IS_ADJECTIVE,
  "improve": IS_VERB,
  "in": IS_PREPOSITION | IS_ADVERB | IS_NOUN,
  "incident": IS_NOUN,
  "incite": IS_VERB,
  "include": IS_VERB,
  "increase": IS_VERB | IS_NOUN,
  "independent": IS_ADJECTIVE,
  "individual": IS_ADJECTIVE | IS_NOUN,
  "industry": IS_NOUN,
  "infect": IS_VERB,
  "inflation": IS_NOUN,
  "influence": IS_NOUN | IS_VERB,
  "inform": IS_VERB,
  "information": IS_NOUN,
  "inject": IS_VERB,
  "injure": IS_VERB,
  "innocent": IS_ADJECTIVE,
  "insane": IS_ADJECTIVE,
  "insect": IS_NOUN,
  "inspect": IS_VERB,
  "instead": IS_ADVERB,
  "instrument": IS_NOUN | IS_VERB,
  "insult": IS_NOUN | IS_VERB,
  "intelligence": IS_NOUN,
  "intelligent": IS_ADJECTIVE,
  "intense": IS_ADJECTIVE,
  "interest": IS_NOUN,
  "interfere": IS_VERB,
  "international": IS_ADJECTIVE,
  "intervene": IS_VERB,
  "invade": IS_VERB,
  "invent": IS_VERB,
  "invest": IS_VERB,
  "investigate": IS_VERB,
  "invite": IS_VERB,
  "involve": IS_VERB,
  "iron": IS_ADJECTIVE | IS_NOUN | IS_VERB,
  "island": IS_NOUN,
  "issue": IS_VERB | IS_NOUN,
  "it": IS_NOUN,
  "jail": IS_VERB | IS_NOUN,
  "jewel": IS_NOUN,
  "job": IS_NOUN,
  "join": IS_NOUN | IS_VERB,
  "joint": IS_NOUN | IS_ADJECTIVE,
  "joke": IS_NOUN | IS_VERB,
  "judge": IS_NOUN | IS_VERB,
  "jump": IS_NOUN | IS_VERB,
  "jury": IS_NOUN,
  "just": IS_ADJECTIVE | IS_ADVERB,
  "keep": IS_VERB,
  "kick": IS_VERB | IS_NOUN,
  "kidnap": IS_VERB,
  "kill": IS_NOUN | IS_VERB,
  "kind": IS_NOUN | IS_ADJECTIVE,
  "kiss": IS_NOUN | IS_VERB,
  "knife": IS_NOUN | IS_VERB,
  "know": IS_VERB,
  "knowledge": IS_NOUN,
  "labor": IS_NOUN | IS_VERB,
  "laboratory": IS_NOUN,
  "lack": IS_NOUN | IS_VERB,
  "lake": IS_NOUN,
  "land": IS_NOUN | IS_VERB,
  "language": IS_NOUN,
  "large": IS_ADJECTIVE,
  "last": IS_ADVERB | IS_ADJECTIVE | IS_DETERMINER,
  "late": IS_ADJECTIVE | IS_ADVERB,
  "laugh": IS_NOUN | IS_VERB,
  "launch": IS_NOUN | IS_VERB,
  "law": IS_NOUN,
  "lead": IS_NOUN | IS_VERB | IS_ADJECTIVE,
  "leak": IS_NOUN | IS_VERB,
  "learn": IS_VERB,
  "leave": IS_VERB,
  "left": IS_ADJECTIVE | IS_ADVERB,
  "legal": IS_ADJECTIVE,
  "legislature": IS_NOUN,
  "lend": IS_VERB,
  "less": IS_ADVERB | IS_DETERMINER | IS_PREPOSITION,
  "let": IS_VERB,
  "letter": IS_NOUN,
  "level": IS_VERB | IS_NOUN | IS_ADJECTIVE,
  "liberal": IS_ADJECTIVE | IS_NOUN,
  "lie": IS_VERB | IS_NOUN,
  "life": IS_NOUN,
  "lift": IS_NOUN | IS_VERB,
  "light": IS_ADJECTIVE | IS_NOUN | IS_VERB | IS_ADVERB,
  "lightning": IS_NOUN,
  "like": IS_NOUN | IS_VERB | IS_ADJECTIVE,
  "limit": IS_NOUN | IS_VERB,
  "line": IS_NOUN | IS_VERB,
  "link": IS_NOUN | IS_VERB,
  "liquid": IS_NOUN | IS_ADJECTIVE,
  "list": IS_NOUN | IS_VERB,
  "listen": IS_VERB,
  "literature": IS_NOUN,
  "little": IS_ADJECTIVE | IS_ADVERB | IS_DETERMINER | IS_NOUN,
  "live": IS_ADJECTIVE | IS_VERB | IS_ADVERB,
  "load": IS_NOUN | IS_VERB,
  "loan": IS_NOUN | IS_VERB,
  "local": IS_ADJECTIVE | IS_ADVERB | IS_NOUN,
  "lonely": IS_ADJECTIVE,
  "long": IS_VERB | IS_ADJECTIVE | IS_ADVERB,
  "look": IS_VERB | IS_NOUN,
  "lose": IS_VERB,
  "loud": IS_ADJECTIVE,
  "love": IS_NOUN | IS_VERB,
  "low": IS_ADJECTIVE | IS_NOUN | IS_ADVERB,
  "loyal": IS_ADJECTIVE,
  "luck": IS_NOUN,
  "machine": IS_NOUN,
  "magazine": IS_NOUN,
  "mail": IS_NOUN | IS_VERB,
  "main": IS_ADJECTIVE,
  "major": IS_ADJECTIVE | IS_NOUN | IS_VERB,
  "majority": IS_NOUN,
  "make": IS_VERB | IS_NOUN,
  "male": IS_NOUN | IS_ADJECTIVE,
  "man": IS_NOUN,
  "manufacture": 0,
  "many": IS_DETERMINER | IS_NOUN | IS_ADJECTIVE,
  "map": IS_NOUN | IS_VERB,
  "march": IS_NOUN | IS_VERB,
  "mark": IS_NOUN | IS_VERB,
  "market": IS_NOUN | IS_VERB,
  "marry": IS_VERB,
  "mass": IS_NOUN | IS_ADJECTIVE,
  "mate": IS_NOUN | IS_VERB,
  "material": IS_ADJECTIVE | IS_NOUN,
  "mathematics": IS_NOUN,
  "matter": IS_NOUN | IS_VERB,
  "may": IS_VERB | IS_NOUN,
  "mayor": IS_NOUN,
  "meal": IS_NOUN,
  "mean": IS_ADJECTIVE | IS_VERB | IS_NOUN,
  "measure": IS_NOUN | IS_VERB,
  "meat": IS_NOUN,
  "media": IS_NOUN,
  "medicine": IS_NOUN,
  "meet": IS_VERB | IS_NOUN,
  "melt": IS_VERB,
  "member": IS_NOUN,
  "memorial": IS_ADJECTIVE | IS_NOUN,
  "memory": IS_NOUN,
  "mental": IS_ADJECTIVE,
  "mercy": IS_NOUN,
  "message": IS_NOUN | IS_VERB,
  "metal": IS_NOUN | IS_ADJECTIVE,
  "method": IS_NOUN,
  "microscope": IS_NOUN,
  "middle": IS_NOUN | IS_ADJECTIVE,
  "militant": IS_ADJECTIVE,
  "military": IS_ADJECTIVE | IS_NOUN,
  "milk": IS_NOUN | IS_VERB,
  "mind": IS_NOUN | IS_VERB,
  "mine": IS_NOUN | IS_VERB,
  "mineral": IS_ADJECTIVE | IS_NOUN,
  "minister": IS_NOUN | IS_VERB,
  "minor": IS_ADJECTIVE | IS_NOUN | IS_VERB,
  "minority": IS_NOUN | IS_ADJECTIVE,
  "minute": IS_NOUN | IS_ADJECTIVE,
  "miss": IS_VERB | IS_NOUN,
  "missile": IS_NOUN,
  "missing": IS_ADJECTIVE,
  "mistake": IS_NOUN | IS_VERB,
  "mix": IS_VERB | IS_NOUN,
  "mob": IS_NOUN | IS_VERB,
  "model": IS_NOUN | IS_ADJECTIVE | IS_VERB,
  "moderate": IS_ADJECTIVE | IS_NOUN | IS_VERB,
  "modern": IS_ADJECTIVE,
  "money": IS_NOUN,
  "month": IS_NOUN,
  "moon": IS_NOUN | IS_VERB,
  "moral": IS_ADJECTIVE | IS_NOUN,
  "more": IS_DETERMINER | IS_ADVERB,
  "morning": IS_NOUN,
  "most": IS_DETERMINER | IS_ADVERB,
  "mother": IS_NOUN | IS_VERB,
  "motion": IS_VERB | IS_NOUN,
  "mountain": IS_NOUN,
  "mourn": IS_VERB,
  "move": IS_VERB | IS_NOUN,
  "movement": IS_NOUN,
  "movie": IS_NOUN,
  "much": IS_DETERMINER | IS_ADVERB,
  "murder": IS_NOUN | IS_VERB,
  "music": IS_NOUN,
  "must": IS_NOUN | IS_VERB,
  "mystery": IS_NOUN,
  "name": IS_NOUN | IS_VERB,
  "narrow": IS_ADJECTIVE | IS_VERB,
  "nation": IS_NOUN,
  "native": IS_ADJECTIVE | IS_NOUN,
  "natural": IS_ADJECTIVE,
  "nature": IS_NOUN,
  "navy": IS_NOUN | IS_ADJECTIVE,
  "near": IS_ADJECTIVE | IS_ADVERB | IS_PREPOSITION,
  "necessary": IS_ADJECTIVE,
  "need": IS_NOUN | IS_VERB,
  "negotiate": IS_VERB,
  "neither": IS_DETERMINER | IS_CONJUNCTION | IS_ADVERB,
  "neutral": IS_ADJECTIVE,
  "never": IS_ADVERB,
  "new": IS_ADJECTIVE | IS_ADVERB | IS_NOUN,
  "news": IS_NOUN,
  "next": IS_DETERMINER | IS_ADJECTIVE | IS_ADVERB,
  "nice": IS_ADJECTIVE | IS_ADVERB,
  "night": IS_NOUN,
  "no": IS_DETERMINER | IS_ADVERB | IS_PREPOSITION | IS_NOUN,
  "noise": IS_NOUN,
  "nominate": IS_VERB,
  "noon": IS_NOUN,
  "normal": IS_ADJECTIVE | IS_NOUN,
  "north": IS_NOUN | IS_ADJECTIVE | IS_ADVERB,
  "not": IS_ADVERB | IS_CONJUNCTION,
  "note": IS_NOUN | IS_VERB,
  "nothing": IS_NOUN,
  "now": IS_ADJECTIVE | IS_ADVERB | IS_CONJUNCTION | IS_NOUN,
  "nowhere": IS_ADJECTIVE | IS_ADVERB | IS_NOUN,
  "nuclear": IS_ADJECTIVE,
  "number": IS_NOUN | IS_VERB,
  "obey": IS_VERB,
  "object": IS_NOUN | IS_VERB,
  "observe": IS_VERB,
  "occupy": IS_VERB,
  "ocean": IS_NOUN,
  "of": IS_PREPOSITION,
  "off": IS_ADVERB | IS_ADJECTIVE | IS_PREPOSITION,
  "offensive": IS_ADJECTIVE,
  "offer": IS_NOUN | IS_VERB,
  "office": IS_NOUN,
  "officer": IS_NOUN,
  "official": IS_ADJECTIVE,
  "often": IS_ADVERB,
  "oil": IS_NOUN | IS_VERB,
  "old": IS_ADJECTIVE,
  "on": IS_ADJECTIVE | IS_ADVERB | IS_PREPOSITION,
  "once": IS_ADVERB | IS_CONJUNCTION,
  "only": IS_ADJECTIVE | IS_ADVERB | IS_CONJUNCTION,
  "open": IS_ADJECTIVE | IS_VERB,
  "operate": IS_VERB,
  "opinion": IS_NOUN,
  "oppose": IS_VERB,
  "opposite": IS_ADJECTIVE | IS_NOUN | IS_ADVERB | IS_PREPOSITION,
  "oppress": IS_VERB,
  "or": IS_CONJUNCTION,
  "orbit": IS_NOUN | IS_VERB,
  "order": IS_NOUN | IS_VERB,
  "organize": IS_VERB,
  "other": IS_ADJECTIVE | IS_NOUN | IS_DETERMINER | IS_VERB,
  "our": IS_DETERMINER,
  "oust": IS_VERB,
  "out": IS_ADVERB | IS_PREPOSITION | IS_NOUN | IS_VERB | IS_ADJECTIVE,
  "over": IS_ADJECTIVE | IS_ADVERB | IS_PREPOSITION,
  "overthrow": IS_VERB,
  "owe": IS_VERB,
  "own": IS_ADJECTIVE | IS_VERB,
  "pain": IS_NOUN,
  "paint": IS_NOUN | IS_VERB,
  "pan": IS_NOUN | IS_VERB,
  "paper": IS_ADJECTIVE | IS_NOUN | IS_VERB,
  "parachute": IS_NOUN | IS_VERB,
  "parade": IS_NOUN | IS_VERB,
  "pardon": IS_NOUN | IS_VERB,
  "parent": IS_NOUN | IS_VERB,
  "parliament": IS_NOUN,
  "part": IS_NOUN | IS_VERB | IS_ADJECTIVE,
  "party": IS_NOUN | IS_VERB,
  "pass": IS_NOUN | IS_VERB,
  "passenger": IS_NOUN,
  "passport": IS_NOUN,
  "past": IS_NOUN | IS_ADJECTIVE | IS_ADVERB | IS_PREPOSITION,
  "path": IS_NOUN,
  "patient": IS_ADJECTIVE | IS_NOUN,
  "pay": IS_NOUN | IS_VERB | IS_ADJECTIVE,
  "peace": IS_NOUN,
  "people": IS_NOUN,
  "percent": IS_ADVERB | IS_NOUN,
  "perfect": IS_ADJECTIVE | IS_VERB,
  "perform": IS_VERB,
  "period": IS_NOUN | IS_ADJECTIVE,
  "permanent": IS_ADJECTIVE,
  "permit": IS_NOUN | IS_VERB,
  "person": IS_NOUN,
  "physical": IS_ADJECTIVE | IS_NOUN,
  "physics": IS_NOUN,
  "picture": IS_VERB | IS_NOUN,
  "piece": IS_NOUN | IS_VERB,
  "pig": IS_NOUN,
  "pilot": IS_NOUN | IS_ADJECTIVE | IS_VERB,
  "pipe": IS_NOUN | IS_VERB,
  "place": IS_NOUN | IS_VERB,
  "plan": IS_NOUN | IS_VERB,
  "planet": IS_NOUN,
  "plant": IS_NOUN | IS_VERB,
  "plastic": IS_ADJECTIVE | IS_NOUN,
  "play": IS_NOUN | IS_VERB,
  "please": IS_VERB | IS_ADVERB,
  "plenty": IS_NOUN | IS_ADVERB,
  "plot": IS_NOUN | IS_VERB,
  "poem": IS_NOUN,
  "point": IS_NOUN | IS_VERB,
  "poison": IS_NOUN | IS_VERB,
  "police": IS_NOUN | IS_VERB,
  "policy": IS_NOUN,
  "politics": IS_NOUN,
  "pollute": IS_VERB,
  "poor": IS_ADJECTIVE,
  "popular": IS_ADJECTIVE,
  "population": IS_NOUN,
  "port": IS_NOUN,
  "position": IS_NOUN | IS_VERB,
  "possess": IS_VERB,
  "possible": IS_ADJECTIVE,
  "postpone": IS_VERB,
  "pour": IS_VERB | IS_NOUN,
  "poverty": IS_NOUN,
  "power": IS_NOUN | IS_VERB | IS_ADJECTIVE,
  "praise": IS_NOUN | IS_VERB,
  "pray": IS_VERB,
  "pregnant": IS_ADJECTIVE,
  "present": IS_NOUN | IS_VERB | IS_ADJECTIVE,
  "president": IS_NOUN,
  "press": IS_NOUN | IS_VERB,
  "pressure": IS_NOUN,
  "prevent": IS_VERB,
  "price": IS_NOUN | IS_VERB,
  "prison": IS_NOUN,
  "private": IS_ADJECTIVE | IS_NOUN,
  "prize": IS_NOUN | IS_VERB,
  "probably": IS_ADVERB,
  "problem": IS_ADJECTIVE | IS_NOUN,
  "process": IS_NOUN | IS_VERB,
  "produce": IS_NOUN | IS_VERB,
  "profession": IS_NOUN,
  "professor": IS_NOUN,
  "profit": IS_NOUN | IS_VERB,
  "program": IS_NOUN | IS_VERB,
  "progress": IS_NOUN | IS_VERB,
  "project": IS_NOUN | IS_VERB,
  "propaganda": IS_NOUN,
  "property": IS_NOUN,
  "propose": IS_VERB,
  "protect": IS_VERB,
  "protest": IS_VERB | IS_NOUN,
  "prove": IS_VERB,
  "provide": IS_VERB,
  "public": IS_ADJECTIVE | IS_NOUN,
  "publication": IS_NOUN,
  "publish": IS_VERB,
  "pull": IS_VERB | IS_NOUN,
  "pump": IS_VERB | IS_NOUN,
  "punish": IS_VERB,
  "purchase": IS_NOUN | IS_VERB,
  "pure": IS_ADJECTIVE,
  "purpose": IS_NOUN,
  "push": IS_NOUN | IS_VERB,
  "put": IS_VERB,
  "quality": IS_NOUN | IS_ADJECTIVE,
  "question": IS_NOUN | IS_VERB,
  "quick": IS_ADVERB | IS_ADJECTIVE | IS_NOUN,
  "quiet": IS_ADJECTIVE | IS_VERB | IS_NOUN,
  "race": IS_VERB | IS_NOUN,
  "radar": IS_NOUN,
  "radiation": IS_NOUN,
  "radio": IS_NOUN | IS_VERB,
  "raid": IS_NOUN | IS_VERB,
  "railroad": IS_NOUN,
  "rain": IS_NOUN | IS_VERB,
  "raise": IS_NOUN | IS_VERB,
  "rare": IS_ADJECTIVE,
  "rate": IS_NOUN | IS_VERB,
  "reach": IS_NOUN | IS_VERB,
  "react": IS_VERB,
  "read": IS_VERB,
  "ready": IS_ADJECTIVE | IS_VERB,
  "real": IS_ADJECTIVE,
  "realistic": IS_ADJECTIVE,
  "reason": IS_NOUN | IS_VERB,
  "reasonable": IS_ADJECTIVE,
  "rebel": IS_NOUN | IS_VERB,
  "receive": IS_VERB,
  "recent": IS_ADJECTIVE,
  "recession": IS_NOUN,
  "recognize": IS_VERB,
  "record": IS_NOUN | IS_VERB,
  "recover": IS_VERB,
  "red": IS_ADJECTIVE | IS_NOUN,
  "reduce": IS_VERB,
  "reform": IS_NOUN | IS_VERB,
  "refugee": IS_NOUN,
  "refuse": IS_NOUN | IS_VERB,
  "regret": IS_VERB | IS_NOUN,
  "reject": IS_VERB | IS_NOUN,
  "relations": IS_NOUN,
  "release": IS_NOUN | IS_VERB,
  "religion": IS_NOUN,
  "remain": IS_VERB,
  "remains": IS_NOUN,
  "remember": IS_VERB,
  "remove": IS_VERB,
  "repair": IS_VERB,
  "repeat": IS_VERB | IS_NOUN,
  "report": IS_VERB | IS_NOUN,
  "represent": IS_VERB,
  "repress": IS_VERB,
  "request": IS_VERB | IS_NOUN,
  "require": IS_VERB,
  "rescue": IS_VERB | IS_NOUN,
  "research": IS_VERB | IS_NOUN,
  "resign": IS_VERB,
  "resist": IS_VERB,
  "resolution": IS_NOUN,
  "resource": IS_NOUN,
  "responsible": IS_ADJECTIVE,
  "rest": IS_NOUN | IS_VERB,
  "restrain": IS_VERB,
  "restrict": IS_VERB,
  "result": IS_VERB | IS_NOUN,
  "retire": IS_VERB,
  "return": IS_VERB,
  "revolt": IS_NOUN | IS_VERB,
  "rice": IS_NOUN,
  "rich": IS_ADJECTIVE | IS_NOUN,
  "ride": IS_NOUN | IS_VERB,
  "right": IS_ADJECTIVE | IS_ADVERB | IS_NOUN | IS_VERB,
  "riot": IS_NOUN | IS_VERB,
  "rise": IS_NOUN | IS_VERB,
  "risk": IS_NOUN | IS_VERB,
  "river": IS_NOUN,
  "road": IS_NOUN,
  "rob": IS_VERB,
  "rock": IS_NOUN | IS_VERB,
  "rocket": IS_NOUN,
  "roll": IS_NOUN | IS_VERB,
  "room": IS_NOUN,
  "root": IS_NOUN | IS_VERB,
  "rope": IS_NOUN,
  "rough": IS_ADJECTIVE | IS_NOUN | IS_VERB,
  "round": IS_ADJECTIVE | IS_NOUN | IS_VERB,
  "rub": IS_NOUN | IS_VERB,
  "rubber": IS_ADJECTIVE | IS_NOUN,
  "ruin": IS_NOUN | IS_VERB,
  "rule": IS_NOUN | IS_VERB,
  "run": IS_NOUN | IS_VERB,
  "sabotage": IS_NOUN | IS_VERB,
  "sacrifice": IS_NOUN | IS_VERB,
  "sad": IS_ADJECTIVE,
  "safe": IS_ADJECTIVE | IS_NOUN,
  "sail": IS_NOUN | IS_VERB,
  "sailor": IS_NOUN,
  "salt": IS_NOUN | IS_VERB | IS_ADJECTIVE,
  "same": IS_ADJECTIVE,
  "sand": IS_NOUN | IS_ADJECTIVE | IS_VERB,
  "satellite": IS_NOUN,
  "satisfy": IS_VERB,
  "save": IS_VERB,
  "say": IS_VERB | IS_NOUN,
  "school": IS_NOUN,
  "science": IS_NOUN,
  "sea": IS_NOUN,
  "search": IS_NOUN | IS_VERB,
  "season": IS_NOUN | IS_VERB,
  "seat": IS_NOUN | IS_VERB,
  "second": IS_ADJECTIVE | IS_ADVERB | IS_NOUN,
  "secret": IS_ADJECTIVE | IS_NOUN,
  "security": IS_NOUN,
  "see": IS_VERB,
  "seed": IS_VERB | IS_NOUN,
  "seek": IS_VERB,
  "seem": IS_VERB,
  "seize": IS_VERB,
  "self": IS_NOUN | IS_ADJECTIVE,
  "sell": IS_VERB,
  "Senate": IS_NOUN,
  "send": IS_VERB,
  "sense": IS_NOUN | IS_VERB,
  "sentence": IS_NOUN | IS_VERB,
  "separate": IS_ADJECTIVE | IS_VERB,
  "series": IS_NOUN,
  "serious": IS_ADJECTIVE,
  "serve": IS_VERB,
  "service": IS_NOUN | IS_VERB,
  "set": IS_ADJECTIVE | IS_NOUN | IS_VERB,
  "settle": IS_VERB,
  "several": IS_ADJECTIVE | IS_DETERMINER | IS_ADVERB,
  "severe": IS_ADJECTIVE,
  "sex": IS_NOUN,
  "shake": IS_NOUN | IS_VERB,
  "shape": IS_NOUN | IS_VERB,
  "share": IS_NOUN | IS_VERB,
  "sharp": IS_ADJECTIVE,
  "she": 0,
  "sheep": IS_NOUN,
  "shell": IS_NOUN | IS_VERB,
  "shelter": IS_NOUN | IS_VERB,
  "shine": IS_NOUN | IS_VERB,
  "ship": IS_NOUN | IS_VERB,
  "shock": IS_NOUN | IS_VERB,
  "shoe": IS_NOUN,
  "shoot": IS_NOUN | IS_VERB,
  "short": IS_ADJECTIVE | IS_ADVERB | IS_NOUN | IS_VERB,
  "should": IS_VERB,
  "shout": IS_NOUN | IS_VERB,
  "show": IS_NOUN | IS_VERB,
  "shrink": IS_VERB,
  "sick": IS_ADJECTIVE,
  "sickness": IS_NOUN,
  "side": IS_NOUN | IS_ADJECTIVE | IS_VERB,
  "sign": IS_NOUN | IS_VERB,
  "signal": IS_NOUN | IS_VERB,
  "silence": IS_NOUN | IS_VERB,
  "silver": IS_ADJECTIVE | IS_NOUN,
  "similar": IS_ADJECTIVE,
  "simple": IS_ADJECTIVE,
  "since": IS_ADVERB | IS_PREPOSITION | IS_CONJUNCTION,
  "sing": IS_VERB,
  "single": IS_ADJECTIVE,
  "sink": IS_NOUN | IS_VERB,
  "sister": IS_NOUN,
  "sit": IS_VERB,
  "situation": IS_NOUN,
  "size": IS_NOUN | IS_VERB,
  "skeleton": IS_NOUN,
  "skill": IS_NOUN,
  "skin": IS_NOUN,
  "sky": IS_NOUN,
  "slave": IS_NOUN,
  "sleep": IS_NOUN | IS_VERB,
  "slide": IS_NOUN | IS_VERB,
  "slow": IS_ADJECTIVE | IS_VERB,
  "small": IS_ADJECTIVE,
  "smash": IS_VERB,
  "smell": IS_NOUN | IS_VERB,
  "smoke": IS_NOUN | IS_VERB,
  "smooth": IS_ADJECTIVE | IS_VERB,
  "snow": IS_NOUN | IS_VERB,
  "so": IS_CONJUNCTION | IS_ADVERB | IS_ADJECTIVE,
  "social": IS_ADJECTIVE | IS_NOUN,
  "soft": IS_ADJECTIVE,
  "soil": IS_NOUN | IS_VERB,
  "soldier": IS_NOUN,
  "solid": IS_ADJECTIVE | IS_NOUN,
  "solve": IS_VERB,
  "some": IS_DETERMINER | IS_ADVERB,
  "son": IS_NOUN,
  "soon": IS_ADJECTIVE | IS_ADVERB,
  "sort": IS_NOUN | IS_VERB,
  "sound": IS_NOUN | IS_VERB,
  "south": IS_NOUN | IS_ADJECTIVE | IS_ADVERB,
  "space": IS_NOUN,
  "speak": IS_VERB,
  "special": IS_ADJECTIVE | IS_NOUN,
  "speech": IS_NOUN,
  "speed": IS_NOUN | IS_VERB,
  "spend": IS_NOUN | IS_VERB,
  "spill": IS_NOUN | IS_VERB,
  "spirit": IS_NOUN,
  "split": IS_NOUN | IS_VERB,
  "sport": IS_NOUN,
  "spread": IS_NOUN | IS_VERB,
  "spring": IS_NOUN | IS_VERB,
  "spy": IS_NOUN | IS_VERB,
  "square": IS_ADJECTIVE | IS_NOUN | IS_VERB,
  "stab": IS_NOUN | IS_VERB,
  "stand": IS_NOUN | IS_VERB,
  "star": IS_NOUN | IS_VERB,
  "start": IS_NOUN | IS_VERB,
  "starve": IS_VERB,
  "state": IS_NOUN | IS_VERB,
  "station": IS_NOUN | IS_VERB,
  "statue": IS_NOUN,
  "stay": IS_NOUN | IS_VERB,
  "steal": IS_NOUN | IS_VERB,
  "steam": IS_NOUN | IS_VERB,
  "steel": IS_ADJECTIVE | IS_NOUN | IS_VERB,
  "step": IS_NOUN | IS_VERB,
  "stick": IS_NOUN | IS_VERB,
  "still": IS_ADJECTIVE | IS_ADVERB | IS_NOUN,
  "stone": IS_ADJECTIVE | IS_ADVERB | IS_NOUN | IS_VERB,
  "stop": IS_NOUN | IS_VERB,
  "store": IS_NOUN | IS_VERB,
  "storm": IS_NOUN | IS_VERB,
  "story": IS_NOUN,
  "stove": IS_NOUN,
  "straight": IS_ADJECTIVE | IS_ADVERB,
  "strange": IS_ADJECTIVE,
  "street": IS_NOUN,
  "stretch": IS_NOUN | IS_VERB,
  "strike": IS_NOUN | IS_VERB,
  "strong": IS_ADJECTIVE | IS_ADVERB,
  "structure": IS_NOUN,
  "struggle": IS_NOUN | IS_VERB,
  "study": IS_NOUN | IS_VERB,
  "stupid": IS_ADJECTIVE,
  "subject": IS_ADJECTIVE | IS_NOUN,
  "submarine": IS_ADJECTIVE | IS_NOUN,
  "substance": IS_NOUN,
  "substitute": IS_NOUN | IS_VERB,
  "subversion": IS_NOUN,
  "succeed": IS_VERB,
  "such": IS_DETERMINER | IS_NOUN,
  "sudden": IS_ADJECTIVE,
  "suffer": IS_VERB,
  "sugar": IS_NOUN | IS_VERB,
  "suggest": IS_VERB,
  "summer": IS_NOUN,
  "sun": IS_NOUN | IS_VERB,
  "supervise": IS_VERB,
  "supply": IS_NOUN | IS_VERB,
  "support": IS_NOUN | IS_VERB,
  "suppose": IS_VERB,
  "suppress": IS_VERB,
  "sure": IS_ADJECTIVE | IS_ADVERB,
  "surface": IS_NOUN | IS_VERB,
  "surplus": IS_ADJECTIVE | IS_NOUN,
  "surprise": IS_NOUN | IS_VERB,
  "surrender": IS_NOUN | IS_VERB,
  "surround": IS_VERB,
  "survive": IS_VERB,
  "suspect": IS_NOUN | IS_VERB,
  "suspend": IS_VERB,
  "swallow": IS_NOUN | IS_VERB,
  "sweet": IS_ADJECTIVE,
  "swim": IS_NOUN | IS_VERB,
  "sympathy": IS_NOUN,
  "system": IS_NOUN,
  "take": IS_NOUN | IS_VERB,
  "talk": IS_NOUN | IS_VERB,
  "tall": IS_ADJECTIVE,
  "tank": IS_NOUN,
  "target": IS_NOUN | IS_VERB,
  "taste": IS_NOUN | IS_VERB,
  "tax": IS_NOUN | IS_VERB,
  "tea": IS_NOUN,
  "teach": IS_VERB,
  "team": IS_NOUN,
  "tear": IS_NOUN | IS_VERB,
  "tears": IS_NOUN,
  "technical": IS_ADJECTIVE,
  "technology": IS_NOUN,
  "telephone": IS_NOUN | IS_VERB,
  "telescope": IS_NOUN,
  "television": IS_NOUN,
  "tell": IS_NOUN | IS_VERB,
  "temperature": IS_NOUN,
  "temporary": IS_ADJECTIVE,
  "tense": IS_NOUN | IS_ADJECTIVE | IS_VERB,
  "term": IS_NOUN,
  "terrible": IS_ADJECTIVE,
  "territory": IS_NOUN,
  "terror": IS_NOUN,
  "terrorist": IS_NOUN,
  "test": IS_NOUN | IS_VERB,
  "than": IS_CONJUNCTION | IS_PREPOSITION,
  "thank": IS_VERB,
  "that": IS_ADVERB | IS_CONJUNCTION | IS_DETERMINER,
  "the": IS_DETERMINER,
  "theater": IS_NOUN,
  "them": 0, // pronoun
  "then": IS_ADVERB | IS_ADJECTIVE | IS_NOUN,
  "theory": IS_NOUN,
  "there": IS_ADVERB | IS_NOUN,
  "these": IS_DETERMINER,
  "they": 0, // pronoun
  "thick": IS_ADJECTIVE | IS_ADVERB,
  "thin": IS_ADJECTIVE | IS_ADVERB | IS_VERB,
  "thing": IS_NOUN,
  "think": IS_VERB,
  "third": IS_ADJECTIVE | IS_NOUN,
  "this": IS_DETERMINER,
  "threaten": IS_VERB,
  "through": IS_PREPOSITION | IS_ADJECTIVE | IS_ADVERB,
  "throw": IS_NOUN | IS_VERB,
  "tie": IS_NOUN | IS_VERB,
  "time": IS_NOUN | IS_VERB,
  "tired": IS_ADJECTIVE,
  "to": IS_PREPOSITION | IS_ADVERB,
  "today": IS_ADVERB | IS_NOUN,
  "together": IS_ADVERB,
  "tomorrow": IS_ADVERB | IS_NOUN,
  "tonight": IS_ADVERB | IS_NOUN,
  "too": IS_ADVERB,
  "tool": IS_NOUN,
  "top": IS_ADJECTIVE | IS_ADVERB | IS_VERB | IS_NOUN,
  "torture": IS_NOUN | IS_VERB,
  "total": IS_ADJECTIVE | IS_NOUN | IS_VERB,
  "touch": IS_NOUN | IS_VERB,
  "toward": IS_PREPOSITION | IS_ADJECTIVE,
  "town": IS_NOUN,
  "trade": IS_NOUN | IS_VERB,
  "tradition": IS_NOUN,
  "traffic": IS_NOUN | IS_VERB,
  "tragic": IS_ADJECTIVE,
  "train": IS_NOUN | IS_VERB,
  "transport": IS_NOUN | IS_VERB,
  "transportation": IS_NOUN,
  "trap": IS_NOUN | IS_VERB,
  "travel": IS_NOUN | IS_VERB,
  "treason": IS_NOUN,
  "treasure": IS_NOUN | IS_VERB,
  "treat": IS_NOUN | IS_VERB,
  "treatment": IS_NOUN,
  "treaty": IS_NOUN,
  "tree": IS_NOUN,
  "trial": IS_ADJECTIVE | IS_NOUN | IS_VERB,
  "tribe": IS_NOUN,
  "trick": IS_NOUN | IS_VERB,
  "trip": IS_NOUN | IS_VERB,
  "troops": IS_NOUN,
  "trouble": IS_NOUN | IS_VERB,
  "truce": IS_NOUN,
  "truck": IS_NOUN,
  "true": IS_ADJECTIVE | IS_ADVERB | IS_NOUN | IS_VERB,
  "trust": IS_NOUN | IS_VERB,
  "try": IS_NOUN | IS_VERB,
  "tube": IS_NOUN,
  "turn": IS_NOUN | IS_VERB,
  "under": IS_PREPOSITION | IS_ADVERB | IS_ADJECTIVE,
  "understand": IS_VERB,
  "unite": IS_VERB,
  "universe": IS_NOUN,
  "university": IS_NOUN,
  "unless": IS_CONJUNCTION,
  "until": IS_PREPOSITION | IS_CONJUNCTION,
  "up": IS_ADVERB | IS_PREPOSITION | IS_ADJECTIVE | IS_NOUN | IS_VERB,
  "urge": IS_NOUN | IS_VERB,
  "urgent": IS_ADJECTIVE,
  "us": IS_DETERMINER,
  "use": IS_NOUN | IS_VERB,
  "usual": IS_ADJECTIVE | IS_NOUN,
  "valley": IS_NOUN,
  "value": IS_NOUN | IS_VERB,
  "vegetable": IS_NOUN,
  "vehicle": IS_NOUN,
  "version": IS_NOUN,
  "very": IS_ADJECTIVE | IS_ADVERB,
  "veto": IS_NOUN | IS_VERB,
  "vicious": IS_ADJECTIVE,
  "victim": IS_NOUN,
  "victory": IS_NOUN,
  "village": IS_NOUN,
  "violate": IS_VERB,
  "violence": IS_NOUN,
  "visit": IS_NOUN | IS_VERB,
  "voice": IS_NOUN | IS_VERB,
  "volcano": IS_NOUN,
  "vote": IS_NOUN | IS_VERB,
  "wages": IS_NOUN,
  "wait": IS_NOUN | IS_VERB,
  "walk": IS_NOUN | IS_VERB,
  "wall": IS_NOUN,
  "want": IS_NOUN | IS_VERB,
  "war": IS_NOUN | IS_VERB,
  "warm": IS_ADJECTIVE | IS_VERB,
  "warn": IS_VERB,
  "wash": IS_NOUN | IS_VERB,
  "waste": IS_NOUN | IS_VERB,
  "watch": IS_NOUN | IS_VERB,
  "water": IS_NOUN | IS_VERB,
  "wave": IS_NOUN | IS_VERB,
  "way": IS_NOUN,
  "we": IS_DETERMINER,
  "weak": IS_ADJECTIVE,
  "wealth": IS_NOUN,
  "weapon": IS_NOUN,
  "wear": IS_NOUN | IS_VERB,
  "weather": IS_NOUN | IS_VERB,
  "week": IS_NOUN,
  "weigh": IS_VERB,
  "welcome": IS_ADJECTIVE | IS_NOUN | IS_VERB,
  "well": IS_ADVERB | IS_ADJECTIVE,
  "west": IS_NOUN | IS_ADJECTIVE | IS_ADVERB,
  "wet": IS_ADJECTIVE | IS_VERB,
  "what": IS_ADJECTIVE | IS_ADVERB | IS_DETERMINER,
  "wheat": IS_NOUN,
  "wheel": IS_NOUN | IS_VERB,
  "when": IS_CONJUNCTION | IS_ADVERB,
  "where": IS_CONJUNCTION | IS_ADVERB,
  "which": IS_DETERMINER,
  "while": IS_CONJUNCTION | IS_NOUN | IS_VERB,
  "white": IS_ADJECTIVE | IS_NOUN,
  "who": 0,
  "whole": IS_ADJECTIVE | IS_NOUN,
  "why": IS_ADVERB,
  "wide": IS_ADJECTIVE | IS_ADVERB,
  "wife": IS_NOUN,
  "wild": IS_ADJECTIVE,
  "will": IS_NOUN | IS_VERB,
  "willing": IS_ADJECTIVE,
  "win": IS_NOUN | IS_VERB,
  "wind": IS_NOUN | IS_VERB,
  "window": IS_NOUN,
  "winter": IS_NOUN,
  "wire": IS_NOUN | IS_VERB,
  "wise": IS_ADJECTIVE,
  "wish": IS_NOUN | IS_VERB,
  "with": IS_PREPOSITION | IS_ADVERB,
  "withdraw": IS_VERB,
  "without": IS_PREPOSITION,
  "woman": IS_NOUN,
  "wonder": IS_NOUN | IS_VERB,
  "wonderful": IS_ADJECTIVE,
  "wood": IS_NOUN,
  "word": IS_NOUN,
  "work": IS_NOUN | IS_VERB,
  "world": IS_NOUN,
  "worry": IS_NOUN | IS_VERB,
  "worse": IS_ADJECTIVE | IS_ADVERB,
  "worth": IS_ADJECTIVE | IS_NOUN,
  "wound": IS_NOUN | IS_VERB,
  "wreck": IS_NOUN | IS_VERB,
  "wreckage": IS_NOUN,
  "write": IS_VERB,
  "wrong": IS_ADJECTIVE | IS_NOUN | IS_VERB,
  "year": IS_NOUN,
  "yellow": IS_ADJECTIVE | IS_NOUN,
  "yes": IS_NOUN,
  "yesterday": IS_NOUN | IS_ADVERB,
  "yet": IS_CONJUNCTION,
  "you": IS_DETERMINER,
  "young": IS_ADJECTIVE | IS_NOUN,
  "zero": IS_NOUN,
  "zoo": IS_NOUN,
  "atom": IS_NOUN,
  "bacteria": IS_NOUN,
  "cell": IS_NOUN,
  "chromosome": IS_NOUN,
  "compound": IS_ADJECTIVE | IS_NOUN | IS_VERB,
  "dense": IS_ADJECTIVE,
  "electron": IS_NOUN,
  "element": IS_NOUN,
  "enzyme": IS_NOUN,
  "fetus": IS_NOUN,
  "fission": IS_NOUN,
  "fusion": IS_NOUN,
  "gene": IS_NOUN,
  "gravity": IS_NOUN,
  "image": IS_NOUN,
  "laser": IS_NOUN,
  "magnet": IS_NOUN,
  "molecule": IS_NOUN,
  "nerve": IS_NOUN,
  "nucleus": IS_NOUN,
  "nutrient": IS_NOUN,
  "organ": IS_NOUN,
  "organism": IS_NOUN,
  "particle": IS_NOUN,
  "protein": IS_NOUN,
  "robot": IS_NOUN,
  "tissue": IS_NOUN,
  "virus": IS_NOUN,
  "x-rays": IS_NOUN,
  "heart": IS_NOUN,
  "intestines": IS_NOUN,
  "kidney": IS_NOUN,
  "liver": IS_NOUN,
  "lung": IS_NOUN,
  "prostate": IS_NOUN,
  "stomach": IS_NOUN,
  "uterus": IS_NOUN,
};

export const adjectives = () =>
  Object.entries(VOA_MAP)
    .filter((kv) => kv[1] & IS_ADJECTIVE)
    .map((kv) => kv[0]);

export const prepositions = () =>
  Object.entries(VOA_MAP)
    .filter((kv) => kv[1] & IS_PREPOSITION)
    .map((kv) => kv[0]);

export const determiners = () =>
  Object.entries(VOA_MAP)
    .filter((kv) => kv[1] & IS_DETERMINER)
    .map((kv) => kv[0]);
